//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 10:32:01 AM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.shaolin.bmdp.datamodel.common.ExpressionType;
import org.shaolin.javacc.context.ParsingContext;
import org.shaolin.javacc.exception.ParsingException;


/**
 * <p>Java class for OpInvokeWorkflowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OpInvokeWorkflowType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}OpType">
 *       &lt;sequence>
 *         &lt;element name="expression" type="{http://bmdp.shaolin.org/datamodel/Common}ExpressionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="eventConsumer" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="partyType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beforeActionWidget" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nextActionWidget" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OpInvokeWorkflowType", propOrder = {
    "expression"
})
public class OpInvokeWorkflowType
    extends OpType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected ExpressionType expression;
    @XmlAttribute(name = "eventConsumer", required = true)
    protected String eventConsumer;
    @XmlAttribute(name = "partyType", required = true)
    protected String partyType;
    @XmlAttribute(name = "beforeActionWidget")
    protected String beforeActionWidget;
    @XmlAttribute(name = "nextActionWidget")
    protected String nextActionWidget;

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionType }
     *     
     */
    public ExpressionType getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionType }
     *     
     */
    public void setExpression(ExpressionType value) {
        this.expression = value;
    }

    /**
     * Gets the value of the eventConsumer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventConsumer() {
        return eventConsumer;
    }

    /**
     * Sets the value of the eventConsumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventConsumer(String value) {
        this.eventConsumer = value;
    }

    /**
     * Gets the value of the partyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyType() {
        return partyType;
    }

    /**
     * Sets the value of the partyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyType(String value) {
        this.partyType = value;
    }

    /**
     * Gets the value of the beforeActionWidget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeActionWidget() {
        return beforeActionWidget;
    }

    /**
     * Sets the value of the beforeActionWidget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeActionWidget(String value) {
        this.beforeActionWidget = value;
    }

    /**
     * Gets the value of the nextActionWidget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextActionWidget() {
        return nextActionWidget;
    }

    /**
     * Sets the value of the nextActionWidget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextActionWidget(String value) {
        this.nextActionWidget = value;
    }

    public void parse(ParsingContext context) throws ParsingException
    {
    	getExpression().parse(context);
    }

}
