//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.06 at 02:38:27 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UICountDownType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UICountDownType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UITextComponentType">
 *       &lt;sequence>
 *         &lt;element name="format" type="{http://bmdp.shaolin.org/datamodel/Page}StringPropertyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UICountDownType", propOrder = {
    "format"
})
public class UICountDownType
    extends UITextComponentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected StringPropertyType format;

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link StringPropertyType }
     *     
     */
    public StringPropertyType getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPropertyType }
     *     
     */
    public void setFormat(StringPropertyType value) {
        this.format = value;
    }

}
