//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.20 at 02:49:50 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UIPreNextPanelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UIPreNextPanelType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://bmdp.shaolin.org/datamodel/Page}UIComponentType">
 *       &lt;sequence>
 *         &lt;element name="ajaxLoad" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="tabSelected" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="previousAction" type="{http://bmdp.shaolin.org/datamodel/Page}ExpressionPropertyType"/>
 *         &lt;element name="nextAction" type="{http://bmdp.shaolin.org/datamodel/Page}ExpressionPropertyType"/>
 *         &lt;element name="tab" type="{http://bmdp.shaolin.org/datamodel/Page}UITabPaneItemType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UIPreNextPanelType", propOrder = {
    "ajaxLoad",
    "tabSelected",
    "previousAction",
    "nextAction",
    "tabs"
})
public class UIPreNextPanelType
    extends UIComponentType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(defaultValue = "false")
    protected boolean ajaxLoad;
    protected int tabSelected;
    @XmlElement(required = true)
    protected ExpressionPropertyType previousAction;
    @XmlElement(required = true)
    protected ExpressionPropertyType nextAction;
    @XmlElement(name = "tab", required = true)
    protected List<UITabPaneItemType> tabs;

    /**
     * Gets the value of the ajaxLoad property.
     * 
     */
    public boolean isAjaxLoad() {
        return ajaxLoad;
    }

    /**
     * Sets the value of the ajaxLoad property.
     * 
     */
    public void setAjaxLoad(boolean value) {
        this.ajaxLoad = value;
    }

    /**
     * Gets the value of the tabSelected property.
     * 
     */
    public int getTabSelected() {
        return tabSelected;
    }

    /**
     * Sets the value of the tabSelected property.
     * 
     */
    public void setTabSelected(int value) {
        this.tabSelected = value;
    }

    /**
     * Gets the value of the previousAction property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionPropertyType }
     *     
     */
    public ExpressionPropertyType getPreviousAction() {
        return previousAction;
    }

    /**
     * Sets the value of the previousAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionPropertyType }
     *     
     */
    public void setPreviousAction(ExpressionPropertyType value) {
        this.previousAction = value;
    }

    /**
     * Gets the value of the nextAction property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionPropertyType }
     *     
     */
    public ExpressionPropertyType getNextAction() {
        return nextAction;
    }

    /**
     * Sets the value of the nextAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionPropertyType }
     *     
     */
    public void setNextAction(ExpressionPropertyType value) {
        this.nextAction = value;
    }

    /**
     * Gets the value of the tabs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tabs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTabs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UITabPaneItemType }
     * 
     * 
     */
    public List<UITabPaneItemType> getTabs() {
        if (tabs == null) {
            tabs = new ArrayList<UITabPaneItemType>();
        }
        return this.tabs;
    }

}
