//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.09 at 12:06:22 PM CST 
//


package org.shaolin.bmdp.datamodel.page;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UITableStatsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UITableStatsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chart" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tableName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uiFrom" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uiid" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UITableStatsType", propOrder = {
    "charts"
})
public class UITableStatsType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "chart", required = true)
    protected List<String> charts;
    @XmlAttribute(name = "tableName")
    protected String tableName;
    @XmlAttribute(name = "uiFrom")
    protected String uiFrom;
    @XmlAttribute(name = "uiid")
    protected String uiid;

    /**
     * Gets the value of the charts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the charts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCharts() {
        if (charts == null) {
            charts = new ArrayList<String>();
        }
        return this.charts;
    }

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableName(String value) {
        this.tableName = value;
    }

    /**
     * Gets the value of the uiFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiFrom() {
        return uiFrom;
    }

    /**
     * Sets the value of the uiFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiFrom(String value) {
        this.uiFrom = value;
    }

    /**
     * Gets the value of the uiid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiid() {
        return uiid;
    }

    /**
     * Sets the value of the uiid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiid(String value) {
        this.uiid = value;
    }

}
