//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbsSpinner complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbsSpinner">
 *   &lt;complexContent>
 *     &lt;extension base="{}AdapterView">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}entries"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbsSpinner")
@XmlSeeAlso({
    Spinner.class,
    Gallery.class
})
public class AbsSpinner
    extends AdapterView
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "entries", namespace = "http://schemas.android.com/apk/res/android")
    protected String entries;

    /**
     * Gets the value of the entries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntries() {
        return entries;
    }

    /**
     * Sets the value of the entries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntries(String value) {
        this.entries = value;
    }

}
