//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnalogClock complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnalogClock">
 *   &lt;complexContent>
 *     &lt;extension base="{}View">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dial"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}hand_hour"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}hand_minute"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnalogClock")
@XmlRootElement(name = "AnalogClock")
public class AnalogClock
    extends View
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "dial", namespace = "http://schemas.android.com/apk/res/android")
    protected String dial;
    @XmlAttribute(name = "hand_hour", namespace = "http://schemas.android.com/apk/res/android")
    protected String handHour;
    @XmlAttribute(name = "hand_minute", namespace = "http://schemas.android.com/apk/res/android")
    protected String handMinute;

    /**
     * Gets the value of the dial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDial() {
        return dial;
    }

    /**
     * Sets the value of the dial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDial(String value) {
        this.dial = value;
    }

    /**
     * Gets the value of the handHour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandHour() {
        return handHour;
    }

    /**
     * Sets the value of the handHour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandHour(String value) {
        this.handHour = value;
    }

    /**
     * Gets the value of the handMinute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandMinute() {
        return handMinute;
    }

    /**
     * Sets the value of the handMinute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandMinute(String value) {
        this.handMinute = value;
    }

}
