//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutoCompleteTextView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AutoCompleteTextView">
 *   &lt;complexContent>
 *     &lt;extension base="{}EditText">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}completionHintView"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}completionThreshold"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownAnchor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownHeight"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownHorizontalOffset"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownSelector"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownVerticalOffset"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownWidth"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AutoCompleteTextView")
@XmlSeeAlso({
    MultiAutoCompleteTextView.class
})
public class AutoCompleteTextView
    extends EditText
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "completionHintView", namespace = "http://schemas.android.com/apk/res/android")
    protected String completionHintView;
    @XmlAttribute(name = "completionThreshold", namespace = "http://schemas.android.com/apk/res/android")
    protected String completionThreshold;
    @XmlAttribute(name = "dropDownAnchor", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownAnchor;
    @XmlAttribute(name = "dropDownHeight", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownHeight;
    @XmlAttribute(name = "dropDownHorizontalOffset", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownHorizontalOffset;
    @XmlAttribute(name = "dropDownSelector", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownSelector;
    @XmlAttribute(name = "dropDownVerticalOffset", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownVerticalOffset;
    @XmlAttribute(name = "dropDownWidth", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownWidth;

    /**
     * Gets the value of the completionHintView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletionHintView() {
        return completionHintView;
    }

    /**
     * Sets the value of the completionHintView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletionHintView(String value) {
        this.completionHintView = value;
    }

    /**
     * Gets the value of the completionThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletionThreshold() {
        return completionThreshold;
    }

    /**
     * Sets the value of the completionThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletionThreshold(String value) {
        this.completionThreshold = value;
    }

    /**
     * Gets the value of the dropDownAnchor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownAnchor() {
        return dropDownAnchor;
    }

    /**
     * Sets the value of the dropDownAnchor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownAnchor(String value) {
        this.dropDownAnchor = value;
    }

    /**
     * Gets the value of the dropDownHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownHeight() {
        return dropDownHeight;
    }

    /**
     * Sets the value of the dropDownHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownHeight(String value) {
        this.dropDownHeight = value;
    }

    /**
     * Gets the value of the dropDownHorizontalOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownHorizontalOffset() {
        return dropDownHorizontalOffset;
    }

    /**
     * Sets the value of the dropDownHorizontalOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownHorizontalOffset(String value) {
        this.dropDownHorizontalOffset = value;
    }

    /**
     * Gets the value of the dropDownSelector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownSelector() {
        return dropDownSelector;
    }

    /**
     * Sets the value of the dropDownSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownSelector(String value) {
        this.dropDownSelector = value;
    }

    /**
     * Gets the value of the dropDownVerticalOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownVerticalOffset() {
        return dropDownVerticalOffset;
    }

    /**
     * Sets the value of the dropDownVerticalOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownVerticalOffset(String value) {
        this.dropDownVerticalOffset = value;
    }

    /**
     * Gets the value of the dropDownWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownWidth() {
        return dropDownWidth;
    }

    /**
     * Sets the value of the dropDownWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownWidth(String value) {
        this.dropDownWidth = value;
    }

}
