//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalendarView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalendarView">
 *   &lt;complexContent>
 *     &lt;extension base="{}FrameLayout">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dateTextAppearance"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}firstDayOfWeek"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}focusedMonthDateColor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}maxDate"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}minDate"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}selectedDateVerticalBar"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}selectedWeekBackgroundColor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}showWeekNumber"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}shownWeekCount"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}unfocusedMonthDateColor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}weekDayTextAppearance"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}weekNumberColor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}weekSeparatorLineColor"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalendarView")
@XmlRootElement(name = "CalendarView")
public class CalendarView
    extends FrameLayout
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "dateTextAppearance", namespace = "http://schemas.android.com/apk/res/android")
    protected String dateTextAppearance;
    @XmlAttribute(name = "firstDayOfWeek", namespace = "http://schemas.android.com/apk/res/android")
    protected String firstDayOfWeek;
    @XmlAttribute(name = "focusedMonthDateColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String focusedMonthDateColor;
    @XmlAttribute(name = "maxDate", namespace = "http://schemas.android.com/apk/res/android")
    protected String maxDate;
    @XmlAttribute(name = "minDate", namespace = "http://schemas.android.com/apk/res/android")
    protected String minDate;
    @XmlAttribute(name = "selectedDateVerticalBar", namespace = "http://schemas.android.com/apk/res/android")
    protected String selectedDateVerticalBar;
    @XmlAttribute(name = "selectedWeekBackgroundColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String selectedWeekBackgroundColor;
    @XmlAttribute(name = "showWeekNumber", namespace = "http://schemas.android.com/apk/res/android")
    protected String showWeekNumber;
    @XmlAttribute(name = "shownWeekCount", namespace = "http://schemas.android.com/apk/res/android")
    protected String shownWeekCount;
    @XmlAttribute(name = "unfocusedMonthDateColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String unfocusedMonthDateColor;
    @XmlAttribute(name = "weekDayTextAppearance", namespace = "http://schemas.android.com/apk/res/android")
    protected String weekDayTextAppearance;
    @XmlAttribute(name = "weekNumberColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String weekNumberColor;
    @XmlAttribute(name = "weekSeparatorLineColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String weekSeparatorLineColor;

    /**
     * Gets the value of the dateTextAppearance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTextAppearance() {
        return dateTextAppearance;
    }

    /**
     * Sets the value of the dateTextAppearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTextAppearance(String value) {
        this.dateTextAppearance = value;
    }

    /**
     * Gets the value of the firstDayOfWeek property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstDayOfWeek() {
        return firstDayOfWeek;
    }

    /**
     * Sets the value of the firstDayOfWeek property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstDayOfWeek(String value) {
        this.firstDayOfWeek = value;
    }

    /**
     * Gets the value of the focusedMonthDateColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFocusedMonthDateColor() {
        return focusedMonthDateColor;
    }

    /**
     * Sets the value of the focusedMonthDateColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFocusedMonthDateColor(String value) {
        this.focusedMonthDateColor = value;
    }

    /**
     * Gets the value of the maxDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxDate() {
        return maxDate;
    }

    /**
     * Sets the value of the maxDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxDate(String value) {
        this.maxDate = value;
    }

    /**
     * Gets the value of the minDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinDate() {
        return minDate;
    }

    /**
     * Sets the value of the minDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinDate(String value) {
        this.minDate = value;
    }

    /**
     * Gets the value of the selectedDateVerticalBar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedDateVerticalBar() {
        return selectedDateVerticalBar;
    }

    /**
     * Sets the value of the selectedDateVerticalBar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedDateVerticalBar(String value) {
        this.selectedDateVerticalBar = value;
    }

    /**
     * Gets the value of the selectedWeekBackgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectedWeekBackgroundColor() {
        return selectedWeekBackgroundColor;
    }

    /**
     * Sets the value of the selectedWeekBackgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectedWeekBackgroundColor(String value) {
        this.selectedWeekBackgroundColor = value;
    }

    /**
     * Gets the value of the showWeekNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowWeekNumber() {
        return showWeekNumber;
    }

    /**
     * Sets the value of the showWeekNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowWeekNumber(String value) {
        this.showWeekNumber = value;
    }

    /**
     * Gets the value of the shownWeekCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShownWeekCount() {
        return shownWeekCount;
    }

    /**
     * Sets the value of the shownWeekCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShownWeekCount(String value) {
        this.shownWeekCount = value;
    }

    /**
     * Gets the value of the unfocusedMonthDateColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnfocusedMonthDateColor() {
        return unfocusedMonthDateColor;
    }

    /**
     * Sets the value of the unfocusedMonthDateColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnfocusedMonthDateColor(String value) {
        this.unfocusedMonthDateColor = value;
    }

    /**
     * Gets the value of the weekDayTextAppearance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeekDayTextAppearance() {
        return weekDayTextAppearance;
    }

    /**
     * Sets the value of the weekDayTextAppearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeekDayTextAppearance(String value) {
        this.weekDayTextAppearance = value;
    }

    /**
     * Gets the value of the weekNumberColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeekNumberColor() {
        return weekNumberColor;
    }

    /**
     * Sets the value of the weekNumberColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeekNumberColor(String value) {
        this.weekNumberColor = value;
    }

    /**
     * Gets the value of the weekSeparatorLineColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeekSeparatorLineColor() {
        return weekSeparatorLineColor;
    }

    /**
     * Sets the value of the weekSeparatorLineColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeekSeparatorLineColor(String value) {
        this.weekSeparatorLineColor = value;
    }

}
