//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExpandableListView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExpandableListView">
 *   &lt;complexContent>
 *     &lt;extension base="{}ListView">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}childDivider"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}childIndicator"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}childIndicatorLeft"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}childIndicatorRight"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}groupIndicator"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}indicatorLeft"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}indicatorRight"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExpandableListView")
@XmlRootElement(name = "ExpandableListView")
public class ExpandableListView
    extends ListView
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "childDivider", namespace = "http://schemas.android.com/apk/res/android")
    protected String childDivider;
    @XmlAttribute(name = "childIndicator", namespace = "http://schemas.android.com/apk/res/android")
    protected String childIndicator;
    @XmlAttribute(name = "childIndicatorLeft", namespace = "http://schemas.android.com/apk/res/android")
    protected String childIndicatorLeft;
    @XmlAttribute(name = "childIndicatorRight", namespace = "http://schemas.android.com/apk/res/android")
    protected String childIndicatorRight;
    @XmlAttribute(name = "groupIndicator", namespace = "http://schemas.android.com/apk/res/android")
    protected String groupIndicator;
    @XmlAttribute(name = "indicatorLeft", namespace = "http://schemas.android.com/apk/res/android")
    protected String indicatorLeft;
    @XmlAttribute(name = "indicatorRight", namespace = "http://schemas.android.com/apk/res/android")
    protected String indicatorRight;

    /**
     * Gets the value of the childDivider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildDivider() {
        return childDivider;
    }

    /**
     * Sets the value of the childDivider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildDivider(String value) {
        this.childDivider = value;
    }

    /**
     * Gets the value of the childIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildIndicator() {
        return childIndicator;
    }

    /**
     * Sets the value of the childIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildIndicator(String value) {
        this.childIndicator = value;
    }

    /**
     * Gets the value of the childIndicatorLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildIndicatorLeft() {
        return childIndicatorLeft;
    }

    /**
     * Sets the value of the childIndicatorLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildIndicatorLeft(String value) {
        this.childIndicatorLeft = value;
    }

    /**
     * Gets the value of the childIndicatorRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildIndicatorRight() {
        return childIndicatorRight;
    }

    /**
     * Sets the value of the childIndicatorRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildIndicatorRight(String value) {
        this.childIndicatorRight = value;
    }

    /**
     * Gets the value of the groupIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupIndicator() {
        return groupIndicator;
    }

    /**
     * Sets the value of the groupIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupIndicator(String value) {
        this.groupIndicator = value;
    }

    /**
     * Gets the value of the indicatorLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicatorLeft() {
        return indicatorLeft;
    }

    /**
     * Sets the value of the indicatorLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorLeft(String value) {
        this.indicatorLeft = value;
    }

    /**
     * Gets the value of the indicatorRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicatorRight() {
        return indicatorRight;
    }

    /**
     * Sets the value of the indicatorRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicatorRight(String value) {
        this.indicatorRight = value;
    }

}
