//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GridView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GridView">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbsListView">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}columnWidth"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}gravity"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}horizontalSpacing"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}numColumns"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}stretchMode"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}verticalSpacing"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GridView")
@XmlRootElement(name = "GridView")
public class GridView
    extends AbsListView
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "columnWidth", namespace = "http://schemas.android.com/apk/res/android")
    protected String columnWidth;
    @XmlAttribute(name = "gravity", namespace = "http://schemas.android.com/apk/res/android")
    protected String gravity;
    @XmlAttribute(name = "horizontalSpacing", namespace = "http://schemas.android.com/apk/res/android")
    protected String horizontalSpacing;
    @XmlAttribute(name = "numColumns", namespace = "http://schemas.android.com/apk/res/android")
    protected String numColumns;
    @XmlAttribute(name = "stretchMode", namespace = "http://schemas.android.com/apk/res/android")
    protected String stretchMode;
    @XmlAttribute(name = "verticalSpacing", namespace = "http://schemas.android.com/apk/res/android")
    protected String verticalSpacing;

    /**
     * Gets the value of the columnWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnWidth() {
        return columnWidth;
    }

    /**
     * Sets the value of the columnWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnWidth(String value) {
        this.columnWidth = value;
    }

    /**
     * Gets the value of the gravity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGravity() {
        return gravity;
    }

    /**
     * Sets the value of the gravity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGravity(String value) {
        this.gravity = value;
    }

    /**
     * Gets the value of the horizontalSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorizontalSpacing() {
        return horizontalSpacing;
    }

    /**
     * Sets the value of the horizontalSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorizontalSpacing(String value) {
        this.horizontalSpacing = value;
    }

    /**
     * Gets the value of the numColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumColumns() {
        return numColumns;
    }

    /**
     * Sets the value of the numColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumColumns(String value) {
        this.numColumns = value;
    }

    /**
     * Gets the value of the stretchMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStretchMode() {
        return stretchMode;
    }

    /**
     * Sets the value of the stretchMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStretchMode(String value) {
        this.stretchMode = value;
    }

    /**
     * Gets the value of the verticalSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalSpacing() {
        return verticalSpacing;
    }

    /**
     * Sets the value of the verticalSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalSpacing(String value) {
        this.verticalSpacing = value;
    }

}
