//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageView">
 *   &lt;complexContent>
 *     &lt;extension base="{}View">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}adjustViewBounds"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}baseline"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}baselineAlignBottom"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}cropToPadding"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}maxHeight"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}maxWidth"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}scaleType"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}src"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}tint"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageView")
@XmlSeeAlso({
    ImageButton.class,
    QuickContactBadge.class
})
public class ImageView
    extends View
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "adjustViewBounds", namespace = "http://schemas.android.com/apk/res/android")
    protected String adjustViewBounds;
    @XmlAttribute(name = "baseline", namespace = "http://schemas.android.com/apk/res/android")
    protected String baseline;
    @XmlAttribute(name = "baselineAlignBottom", namespace = "http://schemas.android.com/apk/res/android")
    protected String baselineAlignBottom;
    @XmlAttribute(name = "cropToPadding", namespace = "http://schemas.android.com/apk/res/android")
    protected String cropToPadding;
    @XmlAttribute(name = "maxHeight", namespace = "http://schemas.android.com/apk/res/android")
    protected String maxHeight;
    @XmlAttribute(name = "maxWidth", namespace = "http://schemas.android.com/apk/res/android")
    protected String maxWidth;
    @XmlAttribute(name = "scaleType", namespace = "http://schemas.android.com/apk/res/android")
    protected String scaleType;
    @XmlAttribute(name = "src", namespace = "http://schemas.android.com/apk/res/android")
    protected String src;
    @XmlAttribute(name = "tint", namespace = "http://schemas.android.com/apk/res/android")
    protected String tint;

    /**
     * Gets the value of the adjustViewBounds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdjustViewBounds() {
        return adjustViewBounds;
    }

    /**
     * Sets the value of the adjustViewBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdjustViewBounds(String value) {
        this.adjustViewBounds = value;
    }

    /**
     * Gets the value of the baseline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseline() {
        return baseline;
    }

    /**
     * Sets the value of the baseline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseline(String value) {
        this.baseline = value;
    }

    /**
     * Gets the value of the baselineAlignBottom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaselineAlignBottom() {
        return baselineAlignBottom;
    }

    /**
     * Sets the value of the baselineAlignBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaselineAlignBottom(String value) {
        this.baselineAlignBottom = value;
    }

    /**
     * Gets the value of the cropToPadding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCropToPadding() {
        return cropToPadding;
    }

    /**
     * Sets the value of the cropToPadding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCropToPadding(String value) {
        this.cropToPadding = value;
    }

    /**
     * Gets the value of the maxHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxHeight() {
        return maxHeight;
    }

    /**
     * Sets the value of the maxHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxHeight(String value) {
        this.maxHeight = value;
    }

    /**
     * Gets the value of the maxWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxWidth() {
        return maxWidth;
    }

    /**
     * Sets the value of the maxWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxWidth(String value) {
        this.maxWidth = value;
    }

    /**
     * Gets the value of the scaleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScaleType() {
        return scaleType;
    }

    /**
     * Sets the value of the scaleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScaleType(String value) {
        this.scaleType = value;
    }

    /**
     * Gets the value of the src property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrc() {
        return src;
    }

    /**
     * Sets the value of the src property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrc(String value) {
        this.src = value;
    }

    /**
     * Gets the value of the tint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTint() {
        return tint;
    }

    /**
     * Sets the value of the tint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTint(String value) {
        this.tint = value;
    }

}
