//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KeyboardView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KeyboardView">
 *   &lt;complexContent>
 *     &lt;extension base="{}View">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}keyBackground"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}keyPreviewHeight"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}keyPreviewLayout"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}keyPreviewOffset"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}keyTextColor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}keyTextSize"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}labelTextSize"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}popupLayout"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}shadowColor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}shadowRadius"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}verticalCorrection"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KeyboardView")
@XmlRootElement(name = "KeyboardView")
public class KeyboardView
    extends View
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "keyBackground", namespace = "http://schemas.android.com/apk/res/android")
    protected String keyBackground;
    @XmlAttribute(name = "keyPreviewHeight", namespace = "http://schemas.android.com/apk/res/android")
    protected String keyPreviewHeight;
    @XmlAttribute(name = "keyPreviewLayout", namespace = "http://schemas.android.com/apk/res/android")
    protected String keyPreviewLayout;
    @XmlAttribute(name = "keyPreviewOffset", namespace = "http://schemas.android.com/apk/res/android")
    protected String keyPreviewOffset;
    @XmlAttribute(name = "keyTextColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String keyTextColor;
    @XmlAttribute(name = "keyTextSize", namespace = "http://schemas.android.com/apk/res/android")
    protected String keyTextSize;
    @XmlAttribute(name = "labelTextSize", namespace = "http://schemas.android.com/apk/res/android")
    protected String labelTextSize;
    @XmlAttribute(name = "popupLayout", namespace = "http://schemas.android.com/apk/res/android")
    protected String popupLayout;
    @XmlAttribute(name = "shadowColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String shadowColor;
    @XmlAttribute(name = "shadowRadius", namespace = "http://schemas.android.com/apk/res/android")
    protected String shadowRadius;
    @XmlAttribute(name = "verticalCorrection", namespace = "http://schemas.android.com/apk/res/android")
    protected String verticalCorrection;

    /**
     * Gets the value of the keyBackground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyBackground() {
        return keyBackground;
    }

    /**
     * Sets the value of the keyBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyBackground(String value) {
        this.keyBackground = value;
    }

    /**
     * Gets the value of the keyPreviewHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyPreviewHeight() {
        return keyPreviewHeight;
    }

    /**
     * Sets the value of the keyPreviewHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyPreviewHeight(String value) {
        this.keyPreviewHeight = value;
    }

    /**
     * Gets the value of the keyPreviewLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyPreviewLayout() {
        return keyPreviewLayout;
    }

    /**
     * Sets the value of the keyPreviewLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyPreviewLayout(String value) {
        this.keyPreviewLayout = value;
    }

    /**
     * Gets the value of the keyPreviewOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyPreviewOffset() {
        return keyPreviewOffset;
    }

    /**
     * Sets the value of the keyPreviewOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyPreviewOffset(String value) {
        this.keyPreviewOffset = value;
    }

    /**
     * Gets the value of the keyTextColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyTextColor() {
        return keyTextColor;
    }

    /**
     * Sets the value of the keyTextColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyTextColor(String value) {
        this.keyTextColor = value;
    }

    /**
     * Gets the value of the keyTextSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKeyTextSize() {
        return keyTextSize;
    }

    /**
     * Sets the value of the keyTextSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKeyTextSize(String value) {
        this.keyTextSize = value;
    }

    /**
     * Gets the value of the labelTextSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabelTextSize() {
        return labelTextSize;
    }

    /**
     * Sets the value of the labelTextSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabelTextSize(String value) {
        this.labelTextSize = value;
    }

    /**
     * Gets the value of the popupLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopupLayout() {
        return popupLayout;
    }

    /**
     * Sets the value of the popupLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopupLayout(String value) {
        this.popupLayout = value;
    }

    /**
     * Gets the value of the shadowColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadowColor() {
        return shadowColor;
    }

    /**
     * Sets the value of the shadowColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadowColor(String value) {
        this.shadowColor = value;
    }

    /**
     * Gets the value of the shadowRadius property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadowRadius() {
        return shadowRadius;
    }

    /**
     * Sets the value of the shadowRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadowRadius(String value) {
        this.shadowRadius = value;
    }

    /**
     * Gets the value of the verticalCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalCorrection() {
        return verticalCorrection;
    }

    /**
     * Sets the value of the verticalCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalCorrection(String value) {
        this.verticalCorrection = value;
    }

}
