//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for LinearLayout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinearLayout">
 *   &lt;complexContent>
 *     &lt;extension base="{}ViewGroup">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}baselineAligned"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}baselineAlignedChildIndex"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}divider"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dividerPadding"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}gravity"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}measureWithLargestChild"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}orientation"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}showDividers"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}weightSum"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinearLayout")
@XmlSeeAlso({
    ZoomControls.class,
    TableRow.class,
    TableLayout.class,
    TabWidget.class,
    SearchView.class,
    RadioGroup.class,
    NumberPicker.class
})
public class LinearLayout
    extends ViewGroup
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "baselineAligned", namespace = "http://schemas.android.com/apk/res/android")
    protected String baselineAligned;
    @XmlAttribute(name = "baselineAlignedChildIndex", namespace = "http://schemas.android.com/apk/res/android")
    protected String baselineAlignedChildIndex;
    @XmlAttribute(name = "divider", namespace = "http://schemas.android.com/apk/res/android")
    protected String divider;
    @XmlAttribute(name = "dividerPadding", namespace = "http://schemas.android.com/apk/res/android")
    protected String dividerPadding;
    @XmlAttribute(name = "gravity", namespace = "http://schemas.android.com/apk/res/android")
    protected String gravity;
    @XmlAttribute(name = "measureWithLargestChild", namespace = "http://schemas.android.com/apk/res/android")
    protected String measureWithLargestChild;
    @XmlAttribute(name = "orientation", namespace = "http://schemas.android.com/apk/res/android")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String orientation;
    @XmlAttribute(name = "showDividers", namespace = "http://schemas.android.com/apk/res/android")
    protected String showDividers;
    @XmlAttribute(name = "weightSum", namespace = "http://schemas.android.com/apk/res/android")
    protected String weightSum;

    /**
     * Gets the value of the baselineAligned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaselineAligned() {
        return baselineAligned;
    }

    /**
     * Sets the value of the baselineAligned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaselineAligned(String value) {
        this.baselineAligned = value;
    }

    /**
     * Gets the value of the baselineAlignedChildIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaselineAlignedChildIndex() {
        return baselineAlignedChildIndex;
    }

    /**
     * Sets the value of the baselineAlignedChildIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaselineAlignedChildIndex(String value) {
        this.baselineAlignedChildIndex = value;
    }

    /**
     * Gets the value of the divider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDivider() {
        return divider;
    }

    /**
     * Sets the value of the divider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDivider(String value) {
        this.divider = value;
    }

    /**
     * Gets the value of the dividerPadding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDividerPadding() {
        return dividerPadding;
    }

    /**
     * Sets the value of the dividerPadding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDividerPadding(String value) {
        this.dividerPadding = value;
    }

    /**
     * Gets the value of the gravity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGravity() {
        return gravity;
    }

    /**
     * Sets the value of the gravity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGravity(String value) {
        this.gravity = value;
    }

    /**
     * Gets the value of the measureWithLargestChild property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureWithLargestChild() {
        return measureWithLargestChild;
    }

    /**
     * Sets the value of the measureWithLargestChild property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureWithLargestChild(String value) {
        this.measureWithLargestChild = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrientation(String value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the showDividers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowDividers() {
        return showDividers;
    }

    /**
     * Sets the value of the showDividers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowDividers(String value) {
        this.showDividers = value;
    }

    /**
     * Gets the value of the weightSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightSum() {
        return weightSum;
    }

    /**
     * Sets the value of the weightSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightSum(String value) {
        this.weightSum = value;
    }

}
