//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProgressBar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProgressBar">
 *   &lt;complexContent>
 *     &lt;extension base="{}View">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}indeterminateBehavior"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}indeterminateDrawable"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}indeterminateDuration"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}indeterminateOnly"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}interpolator"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}progress"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}progressDrawable"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}secondaryProgress"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProgressBar")
@XmlSeeAlso({
    AbsSeekBar.class
})
public class ProgressBar
    extends View
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "indeterminateBehavior", namespace = "http://schemas.android.com/apk/res/android")
    protected String indeterminateBehavior;
    @XmlAttribute(name = "indeterminateDrawable", namespace = "http://schemas.android.com/apk/res/android")
    protected String indeterminateDrawable;
    @XmlAttribute(name = "indeterminateDuration", namespace = "http://schemas.android.com/apk/res/android")
    protected String indeterminateDuration;
    @XmlAttribute(name = "indeterminateOnly", namespace = "http://schemas.android.com/apk/res/android")
    protected String indeterminateOnly;
    @XmlAttribute(name = "interpolator", namespace = "http://schemas.android.com/apk/res/android")
    protected String interpolator;
    @XmlAttribute(name = "progress", namespace = "http://schemas.android.com/apk/res/android")
    protected String progress;
    @XmlAttribute(name = "progressDrawable", namespace = "http://schemas.android.com/apk/res/android")
    protected String progressDrawable;
    @XmlAttribute(name = "secondaryProgress", namespace = "http://schemas.android.com/apk/res/android")
    protected String secondaryProgress;

    /**
     * Gets the value of the indeterminateBehavior property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndeterminateBehavior() {
        return indeterminateBehavior;
    }

    /**
     * Sets the value of the indeterminateBehavior property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndeterminateBehavior(String value) {
        this.indeterminateBehavior = value;
    }

    /**
     * Gets the value of the indeterminateDrawable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndeterminateDrawable() {
        return indeterminateDrawable;
    }

    /**
     * Sets the value of the indeterminateDrawable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndeterminateDrawable(String value) {
        this.indeterminateDrawable = value;
    }

    /**
     * Gets the value of the indeterminateDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndeterminateDuration() {
        return indeterminateDuration;
    }

    /**
     * Sets the value of the indeterminateDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndeterminateDuration(String value) {
        this.indeterminateDuration = value;
    }

    /**
     * Gets the value of the indeterminateOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndeterminateOnly() {
        return indeterminateOnly;
    }

    /**
     * Sets the value of the indeterminateOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndeterminateOnly(String value) {
        this.indeterminateOnly = value;
    }

    /**
     * Gets the value of the interpolator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterpolator() {
        return interpolator;
    }

    /**
     * Sets the value of the interpolator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterpolator(String value) {
        this.interpolator = value;
    }

    /**
     * Gets the value of the progress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgress(String value) {
        this.progress = value;
    }

    /**
     * Gets the value of the progressDrawable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgressDrawable() {
        return progressDrawable;
    }

    /**
     * Sets the value of the progressDrawable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgressDrawable(String value) {
        this.progressDrawable = value;
    }

    /**
     * Gets the value of the secondaryProgress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryProgress() {
        return secondaryProgress;
    }

    /**
     * Sets the value of the secondaryProgress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryProgress(String value) {
        this.secondaryProgress = value;
    }

}
