//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SeekBar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SeekBar">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbsSeekBar">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}thumb"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}thumbOffset"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeekBar")
@XmlRootElement(name = "SeekBar")
public class SeekBar
    extends AbsSeekBar
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "thumb", namespace = "http://schemas.android.com/apk/res/android")
    protected String thumb;
    @XmlAttribute(name = "thumbOffset", namespace = "http://schemas.android.com/apk/res/android")
    protected String thumbOffset;

    /**
     * Gets the value of the thumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * Sets the value of the thumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumb(String value) {
        this.thumb = value;
    }

    /**
     * Gets the value of the thumbOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbOffset() {
        return thumbOffset;
    }

    /**
     * Sets the value of the thumbOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbOffset(String value) {
        this.thumbOffset = value;
    }

}
