//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SlidingDrawer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SlidingDrawer">
 *   &lt;complexContent>
 *     &lt;extension base="{}ViewGroup">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}allowSingleTap"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}animateOnClick"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}bottomOffset"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}content"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}handle"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}orientation"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}topOffset"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SlidingDrawer")
@XmlRootElement(name = "SlidingDrawer")
public class SlidingDrawer
    extends ViewGroup
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "allowSingleTap", namespace = "http://schemas.android.com/apk/res/android")
    protected String allowSingleTap;
    @XmlAttribute(name = "animateOnClick", namespace = "http://schemas.android.com/apk/res/android")
    protected String animateOnClick;
    @XmlAttribute(name = "bottomOffset", namespace = "http://schemas.android.com/apk/res/android")
    protected String bottomOffset;
    @XmlAttribute(name = "content", namespace = "http://schemas.android.com/apk/res/android")
    protected String content;
    @XmlAttribute(name = "handle", namespace = "http://schemas.android.com/apk/res/android")
    protected String handle;
    @XmlAttribute(name = "orientation", namespace = "http://schemas.android.com/apk/res/android")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String orientation;
    @XmlAttribute(name = "topOffset", namespace = "http://schemas.android.com/apk/res/android")
    protected String topOffset;

    /**
     * Gets the value of the allowSingleTap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowSingleTap() {
        return allowSingleTap;
    }

    /**
     * Sets the value of the allowSingleTap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowSingleTap(String value) {
        this.allowSingleTap = value;
    }

    /**
     * Gets the value of the animateOnClick property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnimateOnClick() {
        return animateOnClick;
    }

    /**
     * Sets the value of the animateOnClick property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnimateOnClick(String value) {
        this.animateOnClick = value;
    }

    /**
     * Gets the value of the bottomOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBottomOffset() {
        return bottomOffset;
    }

    /**
     * Sets the value of the bottomOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBottomOffset(String value) {
        this.bottomOffset = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the handle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandle() {
        return handle;
    }

    /**
     * Sets the value of the handle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandle(String value) {
        this.handle = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrientation(String value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the topOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopOffset() {
        return topOffset;
    }

    /**
     * Sets the value of the topOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopOffset(String value) {
        this.topOffset = value;
    }

}
