//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Spinner complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Spinner">
 *   &lt;complexContent>
 *     &lt;extension base="{}AbsSpinner">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownHorizontalOffset"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownSelector"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownVerticalOffset"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}dropDownWidth"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}gravity"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}popupBackground"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}prompt"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}spinnerMode"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Spinner")
@XmlRootElement(name = "Spinner")
public class Spinner
    extends AbsSpinner
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "dropDownHorizontalOffset", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownHorizontalOffset;
    @XmlAttribute(name = "dropDownSelector", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownSelector;
    @XmlAttribute(name = "dropDownVerticalOffset", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownVerticalOffset;
    @XmlAttribute(name = "dropDownWidth", namespace = "http://schemas.android.com/apk/res/android")
    protected String dropDownWidth;
    @XmlAttribute(name = "gravity", namespace = "http://schemas.android.com/apk/res/android")
    protected String gravity;
    @XmlAttribute(name = "popupBackground", namespace = "http://schemas.android.com/apk/res/android")
    protected String popupBackground;
    @XmlAttribute(name = "prompt", namespace = "http://schemas.android.com/apk/res/android")
    protected String prompt;
    @XmlAttribute(name = "spinnerMode", namespace = "http://schemas.android.com/apk/res/android")
    protected String spinnerMode;

    /**
     * Gets the value of the dropDownHorizontalOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownHorizontalOffset() {
        return dropDownHorizontalOffset;
    }

    /**
     * Sets the value of the dropDownHorizontalOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownHorizontalOffset(String value) {
        this.dropDownHorizontalOffset = value;
    }

    /**
     * Gets the value of the dropDownSelector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownSelector() {
        return dropDownSelector;
    }

    /**
     * Sets the value of the dropDownSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownSelector(String value) {
        this.dropDownSelector = value;
    }

    /**
     * Gets the value of the dropDownVerticalOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownVerticalOffset() {
        return dropDownVerticalOffset;
    }

    /**
     * Sets the value of the dropDownVerticalOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownVerticalOffset(String value) {
        this.dropDownVerticalOffset = value;
    }

    /**
     * Gets the value of the dropDownWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropDownWidth() {
        return dropDownWidth;
    }

    /**
     * Sets the value of the dropDownWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropDownWidth(String value) {
        this.dropDownWidth = value;
    }

    /**
     * Gets the value of the gravity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGravity() {
        return gravity;
    }

    /**
     * Sets the value of the gravity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGravity(String value) {
        this.gravity = value;
    }

    /**
     * Gets the value of the popupBackground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPopupBackground() {
        return popupBackground;
    }

    /**
     * Sets the value of the popupBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPopupBackground(String value) {
        this.popupBackground = value;
    }

    /**
     * Gets the value of the prompt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * Sets the value of the prompt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrompt(String value) {
        this.prompt = value;
    }

    /**
     * Gets the value of the spinnerMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpinnerMode() {
        return spinnerMode;
    }

    /**
     * Sets the value of the spinnerMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpinnerMode(String value) {
        this.spinnerMode = value;
    }

}
