//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Switch complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Switch">
 *   &lt;complexContent>
 *     &lt;extension base="{}CompoundButton">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}switchMinWidth"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}switchPadding"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}switchTextAppearance"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textOff"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textOn"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}thumb"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}thumbTextPadding"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}track"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Switch")
@XmlRootElement(name = "Switch")
public class Switch
    extends CompoundButton
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "switchMinWidth", namespace = "http://schemas.android.com/apk/res/android")
    protected String switchMinWidth;
    @XmlAttribute(name = "switchPadding", namespace = "http://schemas.android.com/apk/res/android")
    protected String switchPadding;
    @XmlAttribute(name = "switchTextAppearance", namespace = "http://schemas.android.com/apk/res/android")
    protected String switchTextAppearance;
    @XmlAttribute(name = "textOff", namespace = "http://schemas.android.com/apk/res/android")
    protected String textOff;
    @XmlAttribute(name = "textOn", namespace = "http://schemas.android.com/apk/res/android")
    protected String textOn;
    @XmlAttribute(name = "thumb", namespace = "http://schemas.android.com/apk/res/android")
    protected String thumb;
    @XmlAttribute(name = "thumbTextPadding", namespace = "http://schemas.android.com/apk/res/android")
    protected String thumbTextPadding;
    @XmlAttribute(name = "track", namespace = "http://schemas.android.com/apk/res/android")
    protected String track;

    /**
     * Gets the value of the switchMinWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchMinWidth() {
        return switchMinWidth;
    }

    /**
     * Sets the value of the switchMinWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchMinWidth(String value) {
        this.switchMinWidth = value;
    }

    /**
     * Gets the value of the switchPadding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchPadding() {
        return switchPadding;
    }

    /**
     * Sets the value of the switchPadding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchPadding(String value) {
        this.switchPadding = value;
    }

    /**
     * Gets the value of the switchTextAppearance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchTextAppearance() {
        return switchTextAppearance;
    }

    /**
     * Sets the value of the switchTextAppearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchTextAppearance(String value) {
        this.switchTextAppearance = value;
    }

    /**
     * Gets the value of the textOff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextOff() {
        return textOff;
    }

    /**
     * Sets the value of the textOff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextOff(String value) {
        this.textOff = value;
    }

    /**
     * Gets the value of the textOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextOn() {
        return textOn;
    }

    /**
     * Sets the value of the textOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextOn(String value) {
        this.textOn = value;
    }

    /**
     * Gets the value of the thumb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * Sets the value of the thumb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumb(String value) {
        this.thumb = value;
    }

    /**
     * Gets the value of the thumbTextPadding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbTextPadding() {
        return thumbTextPadding;
    }

    /**
     * Sets the value of the thumbTextPadding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbTextPadding(String value) {
        this.thumbTextPadding = value;
    }

    /**
     * Gets the value of the track property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrack() {
        return track;
    }

    /**
     * Sets the value of the track property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrack(String value) {
        this.track = value;
    }

}
