//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TableLayout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TableLayout">
 *   &lt;complexContent>
 *     &lt;extension base="{}LinearLayout">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}collapseColumns"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}shrinkColumns"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}stretchColumns"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TableLayout")
@XmlRootElement(name = "TableLayout")
public class TableLayout
    extends LinearLayout
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "collapseColumns", namespace = "http://schemas.android.com/apk/res/android")
    protected String collapseColumns;
    @XmlAttribute(name = "shrinkColumns", namespace = "http://schemas.android.com/apk/res/android")
    protected String shrinkColumns;
    @XmlAttribute(name = "stretchColumns", namespace = "http://schemas.android.com/apk/res/android")
    protected String stretchColumns;

    /**
     * Gets the value of the collapseColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollapseColumns() {
        return collapseColumns;
    }

    /**
     * Sets the value of the collapseColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollapseColumns(String value) {
        this.collapseColumns = value;
    }

    /**
     * Gets the value of the shrinkColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShrinkColumns() {
        return shrinkColumns;
    }

    /**
     * Sets the value of the shrinkColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShrinkColumns(String value) {
        this.shrinkColumns = value;
    }

    /**
     * Gets the value of the stretchColumns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStretchColumns() {
        return stretchColumns;
    }

    /**
     * Sets the value of the stretchColumns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStretchColumns(String value) {
        this.stretchColumns = value;
    }

}
