//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TextView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TextView">
 *   &lt;complexContent>
 *     &lt;extension base="{}View">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}autoText"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}bufferType"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}capitalize"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}cursorVisible"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}digits"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}drawableBottom"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}drawableEnd"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}drawableLeft"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}drawablePadding"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}drawableRight"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}drawableStart"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}drawableTop"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}editable"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}editorExtras"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}ellipsize"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}ems"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}enabled"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}freezesText"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}gravity"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}height"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}hint"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}imeActionId"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}imeActionLabel"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}imeOptions"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}includeFontPadding"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}inputMethod"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}inputType"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}lineSpacingExtra"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}lineSpacingMultiplier"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}lines"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}linksClickable"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}marqueeRepeatLimit"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}maxEms"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}maxHeight"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}maxLength"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}maxLines"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}maxWidth"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}minEms"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}minLines"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}numeric"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}password"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}phoneNumber"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}privateImeOptions"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}scrollHorizontally"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}selectAllOnFocus"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}shadowColor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}shadowDx"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}shadowDy"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}shadowRadius"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}singleLine"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}text"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textAllCaps"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textAppearance"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textColor"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textColorHighlight"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textColorHint"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textColorLink"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textCursorDrawable"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textEditNoPasteWindowLayout"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textEditPasteWindowLayout"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textEditSideNoPasteWindowLayout"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textEditSidePasteWindowLayout"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textEditSuggestionItemLayout"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textIsSelectable"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textScaleX"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textSelectHandle"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textSelectHandleLeft"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textSelectHandleRight"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textSize"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}textStyle"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}typeface"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}width"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TextView")
@XmlSeeAlso({
    DigitalClock.class,
    Chronometer.class,
    CheckedTextView.class,
    Button.class,
    EditText.class
})
public class TextView
    extends View
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "autoText", namespace = "http://schemas.android.com/apk/res/android")
    protected String autoText;
    @XmlAttribute(name = "bufferType", namespace = "http://schemas.android.com/apk/res/android")
    protected String bufferType;
    @XmlAttribute(name = "capitalize", namespace = "http://schemas.android.com/apk/res/android")
    protected String capitalize;
    @XmlAttribute(name = "cursorVisible", namespace = "http://schemas.android.com/apk/res/android")
    protected String cursorVisible;
    @XmlAttribute(name = "digits", namespace = "http://schemas.android.com/apk/res/android")
    protected String digits;
    @XmlAttribute(name = "drawableBottom", namespace = "http://schemas.android.com/apk/res/android")
    protected String drawableBottom;
    @XmlAttribute(name = "drawableEnd", namespace = "http://schemas.android.com/apk/res/android")
    protected String drawableEnd;
    @XmlAttribute(name = "drawableLeft", namespace = "http://schemas.android.com/apk/res/android")
    protected String drawableLeft;
    @XmlAttribute(name = "drawablePadding", namespace = "http://schemas.android.com/apk/res/android")
    protected String drawablePadding;
    @XmlAttribute(name = "drawableRight", namespace = "http://schemas.android.com/apk/res/android")
    protected String drawableRight;
    @XmlAttribute(name = "drawableStart", namespace = "http://schemas.android.com/apk/res/android")
    protected String drawableStart;
    @XmlAttribute(name = "drawableTop", namespace = "http://schemas.android.com/apk/res/android")
    protected String drawableTop;
    @XmlAttribute(name = "editable", namespace = "http://schemas.android.com/apk/res/android")
    protected String editable;
    @XmlAttribute(name = "editorExtras", namespace = "http://schemas.android.com/apk/res/android")
    protected String editorExtras;
    @XmlAttribute(name = "ellipsize", namespace = "http://schemas.android.com/apk/res/android")
    protected String ellipsize;
    @XmlAttribute(name = "ems", namespace = "http://schemas.android.com/apk/res/android")
    protected String ems;
    @XmlAttribute(name = "enabled", namespace = "http://schemas.android.com/apk/res/android")
    protected String enabled;
    @XmlAttribute(name = "freezesText", namespace = "http://schemas.android.com/apk/res/android")
    protected String freezesText;
    @XmlAttribute(name = "gravity", namespace = "http://schemas.android.com/apk/res/android")
    protected String gravity;
    @XmlAttribute(name = "height", namespace = "http://schemas.android.com/apk/res/android")
    protected String height;
    @XmlAttribute(name = "hint", namespace = "http://schemas.android.com/apk/res/android")
    protected String hint;
    @XmlAttribute(name = "imeActionId", namespace = "http://schemas.android.com/apk/res/android")
    protected String imeActionId;
    @XmlAttribute(name = "imeActionLabel", namespace = "http://schemas.android.com/apk/res/android")
    protected String imeActionLabel;
    @XmlAttribute(name = "imeOptions", namespace = "http://schemas.android.com/apk/res/android")
    protected String imeOptions;
    @XmlAttribute(name = "includeFontPadding", namespace = "http://schemas.android.com/apk/res/android")
    protected String includeFontPadding;
    @XmlAttribute(name = "inputMethod", namespace = "http://schemas.android.com/apk/res/android")
    protected String inputMethod;
    @XmlAttribute(name = "inputType", namespace = "http://schemas.android.com/apk/res/android")
    protected String inputType;
    @XmlAttribute(name = "lineSpacingExtra", namespace = "http://schemas.android.com/apk/res/android")
    protected String lineSpacingExtra;
    @XmlAttribute(name = "lineSpacingMultiplier", namespace = "http://schemas.android.com/apk/res/android")
    protected String lineSpacingMultiplier;
    @XmlAttribute(name = "lines", namespace = "http://schemas.android.com/apk/res/android")
    protected String lines;
    @XmlAttribute(name = "linksClickable", namespace = "http://schemas.android.com/apk/res/android")
    protected String linksClickable;
    @XmlAttribute(name = "marqueeRepeatLimit", namespace = "http://schemas.android.com/apk/res/android")
    protected String marqueeRepeatLimit;
    @XmlAttribute(name = "maxEms", namespace = "http://schemas.android.com/apk/res/android")
    protected String maxEms;
    @XmlAttribute(name = "maxHeight", namespace = "http://schemas.android.com/apk/res/android")
    protected String maxHeight;
    @XmlAttribute(name = "maxLength", namespace = "http://schemas.android.com/apk/res/android")
    protected String maxLength;
    @XmlAttribute(name = "maxLines", namespace = "http://schemas.android.com/apk/res/android")
    protected String maxLines;
    @XmlAttribute(name = "maxWidth", namespace = "http://schemas.android.com/apk/res/android")
    protected String maxWidth;
    @XmlAttribute(name = "minEms", namespace = "http://schemas.android.com/apk/res/android")
    protected String minEms;
    @XmlAttribute(name = "minLines", namespace = "http://schemas.android.com/apk/res/android")
    protected String minLines;
    @XmlAttribute(name = "numeric", namespace = "http://schemas.android.com/apk/res/android")
    protected String numeric;
    @XmlAttribute(name = "password", namespace = "http://schemas.android.com/apk/res/android")
    protected String password;
    @XmlAttribute(name = "phoneNumber", namespace = "http://schemas.android.com/apk/res/android")
    protected String phoneNumber;
    @XmlAttribute(name = "privateImeOptions", namespace = "http://schemas.android.com/apk/res/android")
    protected String privateImeOptions;
    @XmlAttribute(name = "scrollHorizontally", namespace = "http://schemas.android.com/apk/res/android")
    protected String scrollHorizontally;
    @XmlAttribute(name = "selectAllOnFocus", namespace = "http://schemas.android.com/apk/res/android")
    protected String selectAllOnFocus;
    @XmlAttribute(name = "shadowColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String shadowColor;
    @XmlAttribute(name = "shadowDx", namespace = "http://schemas.android.com/apk/res/android")
    protected String shadowDx;
    @XmlAttribute(name = "shadowDy", namespace = "http://schemas.android.com/apk/res/android")
    protected String shadowDy;
    @XmlAttribute(name = "shadowRadius", namespace = "http://schemas.android.com/apk/res/android")
    protected String shadowRadius;
    @XmlAttribute(name = "singleLine", namespace = "http://schemas.android.com/apk/res/android")
    protected String singleLine;
    @XmlAttribute(name = "text", namespace = "http://schemas.android.com/apk/res/android")
    protected String text;
    @XmlAttribute(name = "textAllCaps", namespace = "http://schemas.android.com/apk/res/android")
    protected String textAllCaps;
    @XmlAttribute(name = "textAppearance", namespace = "http://schemas.android.com/apk/res/android")
    protected String textAppearance;
    @XmlAttribute(name = "textColor", namespace = "http://schemas.android.com/apk/res/android")
    protected String textColor;
    @XmlAttribute(name = "textColorHighlight", namespace = "http://schemas.android.com/apk/res/android")
    protected String textColorHighlight;
    @XmlAttribute(name = "textColorHint", namespace = "http://schemas.android.com/apk/res/android")
    protected String textColorHint;
    @XmlAttribute(name = "textColorLink", namespace = "http://schemas.android.com/apk/res/android")
    protected String textColorLink;
    @XmlAttribute(name = "textCursorDrawable", namespace = "http://schemas.android.com/apk/res/android")
    protected String textCursorDrawable;
    @XmlAttribute(name = "textEditNoPasteWindowLayout", namespace = "http://schemas.android.com/apk/res/android")
    protected String textEditNoPasteWindowLayout;
    @XmlAttribute(name = "textEditPasteWindowLayout", namespace = "http://schemas.android.com/apk/res/android")
    protected String textEditPasteWindowLayout;
    @XmlAttribute(name = "textEditSideNoPasteWindowLayout", namespace = "http://schemas.android.com/apk/res/android")
    protected String textEditSideNoPasteWindowLayout;
    @XmlAttribute(name = "textEditSidePasteWindowLayout", namespace = "http://schemas.android.com/apk/res/android")
    protected String textEditSidePasteWindowLayout;
    @XmlAttribute(name = "textEditSuggestionItemLayout", namespace = "http://schemas.android.com/apk/res/android")
    protected String textEditSuggestionItemLayout;
    @XmlAttribute(name = "textIsSelectable", namespace = "http://schemas.android.com/apk/res/android")
    protected String textIsSelectable;
    @XmlAttribute(name = "textScaleX", namespace = "http://schemas.android.com/apk/res/android")
    protected String textScaleX;
    @XmlAttribute(name = "textSelectHandle", namespace = "http://schemas.android.com/apk/res/android")
    protected String textSelectHandle;
    @XmlAttribute(name = "textSelectHandleLeft", namespace = "http://schemas.android.com/apk/res/android")
    protected String textSelectHandleLeft;
    @XmlAttribute(name = "textSelectHandleRight", namespace = "http://schemas.android.com/apk/res/android")
    protected String textSelectHandleRight;
    @XmlAttribute(name = "textSize", namespace = "http://schemas.android.com/apk/res/android")
    protected String textSize;
    @XmlAttribute(name = "textStyle", namespace = "http://schemas.android.com/apk/res/android")
    protected String textStyle;
    @XmlAttribute(name = "typeface", namespace = "http://schemas.android.com/apk/res/android")
    protected String typeface;
    @XmlAttribute(name = "width", namespace = "http://schemas.android.com/apk/res/android")
    protected String width;

    /**
     * Gets the value of the autoText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoText() {
        return autoText;
    }

    /**
     * Sets the value of the autoText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoText(String value) {
        this.autoText = value;
    }

    /**
     * Gets the value of the bufferType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBufferType() {
        return bufferType;
    }

    /**
     * Sets the value of the bufferType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBufferType(String value) {
        this.bufferType = value;
    }

    /**
     * Gets the value of the capitalize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapitalize() {
        return capitalize;
    }

    /**
     * Sets the value of the capitalize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapitalize(String value) {
        this.capitalize = value;
    }

    /**
     * Gets the value of the cursorVisible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCursorVisible() {
        return cursorVisible;
    }

    /**
     * Sets the value of the cursorVisible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCursorVisible(String value) {
        this.cursorVisible = value;
    }

    /**
     * Gets the value of the digits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigits() {
        return digits;
    }

    /**
     * Sets the value of the digits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigits(String value) {
        this.digits = value;
    }

    /**
     * Gets the value of the drawableBottom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawableBottom() {
        return drawableBottom;
    }

    /**
     * Sets the value of the drawableBottom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawableBottom(String value) {
        this.drawableBottom = value;
    }

    /**
     * Gets the value of the drawableEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawableEnd() {
        return drawableEnd;
    }

    /**
     * Sets the value of the drawableEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawableEnd(String value) {
        this.drawableEnd = value;
    }

    /**
     * Gets the value of the drawableLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawableLeft() {
        return drawableLeft;
    }

    /**
     * Sets the value of the drawableLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawableLeft(String value) {
        this.drawableLeft = value;
    }

    /**
     * Gets the value of the drawablePadding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawablePadding() {
        return drawablePadding;
    }

    /**
     * Sets the value of the drawablePadding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawablePadding(String value) {
        this.drawablePadding = value;
    }

    /**
     * Gets the value of the drawableRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawableRight() {
        return drawableRight;
    }

    /**
     * Sets the value of the drawableRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawableRight(String value) {
        this.drawableRight = value;
    }

    /**
     * Gets the value of the drawableStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawableStart() {
        return drawableStart;
    }

    /**
     * Sets the value of the drawableStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawableStart(String value) {
        this.drawableStart = value;
    }

    /**
     * Gets the value of the drawableTop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawableTop() {
        return drawableTop;
    }

    /**
     * Sets the value of the drawableTop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawableTop(String value) {
        this.drawableTop = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditable() {
        return editable;
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditable(String value) {
        this.editable = value;
    }

    /**
     * Gets the value of the editorExtras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditorExtras() {
        return editorExtras;
    }

    /**
     * Sets the value of the editorExtras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditorExtras(String value) {
        this.editorExtras = value;
    }

    /**
     * Gets the value of the ellipsize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEllipsize() {
        return ellipsize;
    }

    /**
     * Sets the value of the ellipsize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEllipsize(String value) {
        this.ellipsize = value;
    }

    /**
     * Gets the value of the ems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEms() {
        return ems;
    }

    /**
     * Sets the value of the ems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEms(String value) {
        this.ems = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnabled(String value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the freezesText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreezesText() {
        return freezesText;
    }

    /**
     * Sets the value of the freezesText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreezesText(String value) {
        this.freezesText = value;
    }

    /**
     * Gets the value of the gravity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGravity() {
        return gravity;
    }

    /**
     * Sets the value of the gravity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGravity(String value) {
        this.gravity = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeight(String value) {
        this.height = value;
    }

    /**
     * Gets the value of the hint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHint() {
        return hint;
    }

    /**
     * Sets the value of the hint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHint(String value) {
        this.hint = value;
    }

    /**
     * Gets the value of the imeActionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeActionId() {
        return imeActionId;
    }

    /**
     * Sets the value of the imeActionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeActionId(String value) {
        this.imeActionId = value;
    }

    /**
     * Gets the value of the imeActionLabel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeActionLabel() {
        return imeActionLabel;
    }

    /**
     * Sets the value of the imeActionLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeActionLabel(String value) {
        this.imeActionLabel = value;
    }

    /**
     * Gets the value of the imeOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImeOptions() {
        return imeOptions;
    }

    /**
     * Sets the value of the imeOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImeOptions(String value) {
        this.imeOptions = value;
    }

    /**
     * Gets the value of the includeFontPadding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncludeFontPadding() {
        return includeFontPadding;
    }

    /**
     * Sets the value of the includeFontPadding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncludeFontPadding(String value) {
        this.includeFontPadding = value;
    }

    /**
     * Gets the value of the inputMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputMethod() {
        return inputMethod;
    }

    /**
     * Sets the value of the inputMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputMethod(String value) {
        this.inputMethod = value;
    }

    /**
     * Gets the value of the inputType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputType() {
        return inputType;
    }

    /**
     * Sets the value of the inputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputType(String value) {
        this.inputType = value;
    }

    /**
     * Gets the value of the lineSpacingExtra property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineSpacingExtra() {
        return lineSpacingExtra;
    }

    /**
     * Sets the value of the lineSpacingExtra property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineSpacingExtra(String value) {
        this.lineSpacingExtra = value;
    }

    /**
     * Gets the value of the lineSpacingMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineSpacingMultiplier() {
        return lineSpacingMultiplier;
    }

    /**
     * Sets the value of the lineSpacingMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineSpacingMultiplier(String value) {
        this.lineSpacingMultiplier = value;
    }

    /**
     * Gets the value of the lines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLines() {
        return lines;
    }

    /**
     * Sets the value of the lines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLines(String value) {
        this.lines = value;
    }

    /**
     * Gets the value of the linksClickable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinksClickable() {
        return linksClickable;
    }

    /**
     * Sets the value of the linksClickable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinksClickable(String value) {
        this.linksClickable = value;
    }

    /**
     * Gets the value of the marqueeRepeatLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarqueeRepeatLimit() {
        return marqueeRepeatLimit;
    }

    /**
     * Sets the value of the marqueeRepeatLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarqueeRepeatLimit(String value) {
        this.marqueeRepeatLimit = value;
    }

    /**
     * Gets the value of the maxEms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxEms() {
        return maxEms;
    }

    /**
     * Sets the value of the maxEms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxEms(String value) {
        this.maxEms = value;
    }

    /**
     * Gets the value of the maxHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxHeight() {
        return maxHeight;
    }

    /**
     * Sets the value of the maxHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxHeight(String value) {
        this.maxHeight = value;
    }

    /**
     * Gets the value of the maxLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxLength() {
        return maxLength;
    }

    /**
     * Sets the value of the maxLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxLength(String value) {
        this.maxLength = value;
    }

    /**
     * Gets the value of the maxLines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxLines() {
        return maxLines;
    }

    /**
     * Sets the value of the maxLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxLines(String value) {
        this.maxLines = value;
    }

    /**
     * Gets the value of the maxWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxWidth() {
        return maxWidth;
    }

    /**
     * Sets the value of the maxWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxWidth(String value) {
        this.maxWidth = value;
    }

    /**
     * Gets the value of the minEms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinEms() {
        return minEms;
    }

    /**
     * Sets the value of the minEms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinEms(String value) {
        this.minEms = value;
    }

    /**
     * Gets the value of the minLines property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinLines() {
        return minLines;
    }

    /**
     * Sets the value of the minLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinLines(String value) {
        this.minLines = value;
    }

    /**
     * Gets the value of the numeric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeric() {
        return numeric;
    }

    /**
     * Sets the value of the numeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeric(String value) {
        this.numeric = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the privateImeOptions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrivateImeOptions() {
        return privateImeOptions;
    }

    /**
     * Sets the value of the privateImeOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrivateImeOptions(String value) {
        this.privateImeOptions = value;
    }

    /**
     * Gets the value of the scrollHorizontally property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrollHorizontally() {
        return scrollHorizontally;
    }

    /**
     * Sets the value of the scrollHorizontally property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrollHorizontally(String value) {
        this.scrollHorizontally = value;
    }

    /**
     * Gets the value of the selectAllOnFocus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectAllOnFocus() {
        return selectAllOnFocus;
    }

    /**
     * Sets the value of the selectAllOnFocus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectAllOnFocus(String value) {
        this.selectAllOnFocus = value;
    }

    /**
     * Gets the value of the shadowColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadowColor() {
        return shadowColor;
    }

    /**
     * Sets the value of the shadowColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadowColor(String value) {
        this.shadowColor = value;
    }

    /**
     * Gets the value of the shadowDx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadowDx() {
        return shadowDx;
    }

    /**
     * Sets the value of the shadowDx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadowDx(String value) {
        this.shadowDx = value;
    }

    /**
     * Gets the value of the shadowDy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadowDy() {
        return shadowDy;
    }

    /**
     * Sets the value of the shadowDy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadowDy(String value) {
        this.shadowDy = value;
    }

    /**
     * Gets the value of the shadowRadius property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShadowRadius() {
        return shadowRadius;
    }

    /**
     * Sets the value of the shadowRadius property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShadowRadius(String value) {
        this.shadowRadius = value;
    }

    /**
     * Gets the value of the singleLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSingleLine() {
        return singleLine;
    }

    /**
     * Sets the value of the singleLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSingleLine(String value) {
        this.singleLine = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the textAllCaps property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextAllCaps() {
        return textAllCaps;
    }

    /**
     * Sets the value of the textAllCaps property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextAllCaps(String value) {
        this.textAllCaps = value;
    }

    /**
     * Gets the value of the textAppearance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextAppearance() {
        return textAppearance;
    }

    /**
     * Sets the value of the textAppearance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextAppearance(String value) {
        this.textAppearance = value;
    }

    /**
     * Gets the value of the textColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColor() {
        return textColor;
    }

    /**
     * Sets the value of the textColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColor(String value) {
        this.textColor = value;
    }

    /**
     * Gets the value of the textColorHighlight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColorHighlight() {
        return textColorHighlight;
    }

    /**
     * Sets the value of the textColorHighlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColorHighlight(String value) {
        this.textColorHighlight = value;
    }

    /**
     * Gets the value of the textColorHint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColorHint() {
        return textColorHint;
    }

    /**
     * Sets the value of the textColorHint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColorHint(String value) {
        this.textColorHint = value;
    }

    /**
     * Gets the value of the textColorLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextColorLink() {
        return textColorLink;
    }

    /**
     * Sets the value of the textColorLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextColorLink(String value) {
        this.textColorLink = value;
    }

    /**
     * Gets the value of the textCursorDrawable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextCursorDrawable() {
        return textCursorDrawable;
    }

    /**
     * Sets the value of the textCursorDrawable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextCursorDrawable(String value) {
        this.textCursorDrawable = value;
    }

    /**
     * Gets the value of the textEditNoPasteWindowLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextEditNoPasteWindowLayout() {
        return textEditNoPasteWindowLayout;
    }

    /**
     * Sets the value of the textEditNoPasteWindowLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextEditNoPasteWindowLayout(String value) {
        this.textEditNoPasteWindowLayout = value;
    }

    /**
     * Gets the value of the textEditPasteWindowLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextEditPasteWindowLayout() {
        return textEditPasteWindowLayout;
    }

    /**
     * Sets the value of the textEditPasteWindowLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextEditPasteWindowLayout(String value) {
        this.textEditPasteWindowLayout = value;
    }

    /**
     * Gets the value of the textEditSideNoPasteWindowLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextEditSideNoPasteWindowLayout() {
        return textEditSideNoPasteWindowLayout;
    }

    /**
     * Sets the value of the textEditSideNoPasteWindowLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextEditSideNoPasteWindowLayout(String value) {
        this.textEditSideNoPasteWindowLayout = value;
    }

    /**
     * Gets the value of the textEditSidePasteWindowLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextEditSidePasteWindowLayout() {
        return textEditSidePasteWindowLayout;
    }

    /**
     * Sets the value of the textEditSidePasteWindowLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextEditSidePasteWindowLayout(String value) {
        this.textEditSidePasteWindowLayout = value;
    }

    /**
     * Gets the value of the textEditSuggestionItemLayout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextEditSuggestionItemLayout() {
        return textEditSuggestionItemLayout;
    }

    /**
     * Sets the value of the textEditSuggestionItemLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextEditSuggestionItemLayout(String value) {
        this.textEditSuggestionItemLayout = value;
    }

    /**
     * Gets the value of the textIsSelectable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextIsSelectable() {
        return textIsSelectable;
    }

    /**
     * Sets the value of the textIsSelectable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextIsSelectable(String value) {
        this.textIsSelectable = value;
    }

    /**
     * Gets the value of the textScaleX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextScaleX() {
        return textScaleX;
    }

    /**
     * Sets the value of the textScaleX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextScaleX(String value) {
        this.textScaleX = value;
    }

    /**
     * Gets the value of the textSelectHandle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSelectHandle() {
        return textSelectHandle;
    }

    /**
     * Sets the value of the textSelectHandle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSelectHandle(String value) {
        this.textSelectHandle = value;
    }

    /**
     * Gets the value of the textSelectHandleLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSelectHandleLeft() {
        return textSelectHandleLeft;
    }

    /**
     * Sets the value of the textSelectHandleLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSelectHandleLeft(String value) {
        this.textSelectHandleLeft = value;
    }

    /**
     * Gets the value of the textSelectHandleRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSelectHandleRight() {
        return textSelectHandleRight;
    }

    /**
     * Sets the value of the textSelectHandleRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSelectHandleRight(String value) {
        this.textSelectHandleRight = value;
    }

    /**
     * Gets the value of the textSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextSize() {
        return textSize;
    }

    /**
     * Sets the value of the textSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextSize(String value) {
        this.textSize = value;
    }

    /**
     * Gets the value of the textStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextStyle() {
        return textStyle;
    }

    /**
     * Sets the value of the textStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextStyle(String value) {
        this.textStyle = value;
    }

    /**
     * Gets the value of the typeface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeface() {
        return typeface;
    }

    /**
     * Sets the value of the typeface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeface(String value) {
        this.typeface = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

}
