//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.28 at 04:10:22 PM CST 
//


package org.shaolin.bmdp.designtime.andriod.datamodel;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ViewFlipper complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewFlipper">
 *   &lt;complexContent>
 *     &lt;extension base="{}ViewAnimator">
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}autoStart"/>
 *       &lt;attribute ref="{http://schemas.android.com/apk/res/android}flipInterval"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewFlipper")
@XmlRootElement(name = "ViewFlipper")
public class ViewFlipper
    extends ViewAnimator
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlAttribute(name = "autoStart", namespace = "http://schemas.android.com/apk/res/android")
    protected String autoStart;
    @XmlAttribute(name = "flipInterval", namespace = "http://schemas.android.com/apk/res/android")
    protected String flipInterval;

    /**
     * Gets the value of the autoStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoStart() {
        return autoStart;
    }

    /**
     * Sets the value of the autoStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoStart(String value) {
        this.autoStart = value;
    }

    /**
     * Gets the value of the flipInterval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlipInterval() {
        return flipInterval;
    }

    /**
     * Sets the value of the flipInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlipInterval(String value) {
        this.flipInterval = value;
    }

}
