/*
 *
 * This file is automatically generated on Mon Jun 16 22:29:19 CST 2014
 */

    
package org.shaolin.uimaster.test.be;
        
import org.shaolin.bmdp.json.JSONException;
import org.shaolin.bmdp.json.JSONObject;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;
import org.shaolin.uimaster.test.ce.Gender;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class CustomerImpl  implements org.shaolin.uimaster.test.be.ICustomer
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    protected String getBusinessEntityName()
    {
        return "org.shaolin.uimaster.test.be.Customer";
    }

    public CustomerImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    private IAddress address = new AddressImpl();
    
    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String name;
    
    protected Gender gender;
    
    public Gender getGender() {
		return gender;
	}

	public void setGender(Gender gender) {
		this.gender = gender;
	}

	/**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get name
     *
     *  @return name
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set name
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    public boolean isEnabled() {
    	return true;
    }
    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.uimaster.test.be.CustomerImpl))
            return false;
        org.shaolin.uimaster.test.be.CustomerImpl o = (org.shaolin.uimaster.test.be.CustomerImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
    	return (new JSONObject(this)).toString();
    }
    
    public ICustomer createEntity ()
    {
        return new CustomerImpl();
    }

	@Override
	public void setAddress(IAddress address) {
		this.address = address;
	}

	@Override
	public IAddress getAddress() {
		return address;
	}

	@Override
	public JSONObject toJSON() throws JSONException {
		return new JSONObject(this);
	}

	@Override
	public void fromJSON(JSONObject json) throws JSONException {
		
	}
    
}

        

