/*
 *
 * This file is automatically generated on Fri Mar 11 00:00:41 CST 2016
 */

    
package org.shaolin.bmdp.workflow.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.ITaskEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class ChatHistoryImpl  implements org.shaolin.bmdp.workflow.be.IChatHistory
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final transient IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.bmdp.workflow.be.ChatHistory";
    }

    public ChatHistoryImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Create Date
     */
    private java.util.Date createDate = null;

    /**
     * Enable record
     */
    private boolean _enable = true;

    /**
     *  set orgId
     *  @parameter orgId.
     */
    private long orgId = 0;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected long taskId;
    
   /**
     *  help is not available
     */    
    protected long sentPartyId;
    
   /**
     *  help is not available
     */    
    protected long receivedPartyId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String message;
    
   /**
     *  help is not available
     */    
    protected boolean read;
    
        /**
     *  Get createDate
     *
     *  @return java.util.Date
     */
    public java.util.Date getCreateDate() {
        return createDate;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
            /**
     *  get orgId
     */
    public long getOrgId() {
        return this.orgId;
    }

    
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get taskId
     *
     *  @return taskId
     */
    public long getTaskId() {
        return taskId;
    }

    /**
     *  get sentPartyId
     *
     *  @return sentPartyId
     */
    public long getSentPartyId() {
        return sentPartyId;
    }

    /**
     *  get receivedPartyId
     *
     *  @return receivedPartyId
     */
    public long getReceivedPartyId() {
        return receivedPartyId;
    }

    /**
     *  get message
     *
     *  @return message
     */
    public java.lang.String getMessage() {
        return message;
    }

    /**
     *  get read
     *
     *  @return read
     */
    public boolean getRead() {
        return read;
    }

        /**
     *  set createDate
     *  @parameter true or false.
     */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

        /**
     *  set orgId
     *  @parameter orgId.
     */
    public void setOrgId(long orgId) {
        this.orgId = orgId;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set taskId
     */
    public void setTaskId(long taskId) {
        this.taskId = taskId;
    }

    /**
     *  set sentPartyId
     */
    public void setSentPartyId(long sentPartyId) {
        this.sentPartyId = sentPartyId;
    }

    /**
     *  set receivedPartyId
     */
    public void setReceivedPartyId(long receivedPartyId) {
        this.receivedPartyId = receivedPartyId;
    }

    /**
     *  set message
     */
    public void setMessage(java.lang.String message) {
        this.message = message;
    }

    /**
     *  set read
     */
    public void setRead(boolean read) {
        this.read = read;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.bmdp.workflow.be.ChatHistoryImpl))
            return false;
        org.shaolin.bmdp.workflow.be.ChatHistoryImpl o = (org.shaolin.bmdp.workflow.be.ChatHistoryImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.bmdp.workflow.be.ChatHistory");
    
        aBuf.append(" : ");
        
        aBuf.append("createDate=").append(createDate).append(", ");
        
        aBuf.append("orgId=").append(orgId);
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("taskId");
        aBuf.append("=");
        aBuf.append(taskId);
        aBuf.append(", ");
        
        aBuf.append("sentPartyId");
        aBuf.append("=");
        aBuf.append(sentPartyId);
        aBuf.append(", ");
        
        aBuf.append("receivedPartyId");
        aBuf.append("=");
        aBuf.append(receivedPartyId);
        aBuf.append(", ");
        
        aBuf.append("message");
        aBuf.append("=");
        aBuf.append(message);
        aBuf.append(", ");
        
        aBuf.append("read");
        aBuf.append("=");
        aBuf.append(read);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType taskIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for taskId
        member = new MemberType();
        member.setName("taskId");
        member.setDescription("null");
        member.setType(taskIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType sentPartyIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for sentPartyId
        member = new MemberType();
        member.setName("sentPartyId");
        member.setDescription("null");
        member.setType(sentPartyIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.LongType receivedPartyIdBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for receivedPartyId
        member = new MemberType();
        member.setName("receivedPartyId");
        member.setDescription("null");
        member.setType(receivedPartyIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType messageBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for message
        member = new MemberType();
        member.setName("message");
        member.setDescription("null");
        member.setType(messageBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.BooleanType readBEType = new org.shaolin.bmdp.datamodel.bediagram.BooleanType();
    
        //MemberType Define for read
        member = new MemberType();
        member.setName("read");
        member.setDescription("null");
        member.setType(readBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IChatHistory createEntity ()
    {
        return new ChatHistoryImpl();
    }
    
}

        

