/*
 *
 * This file is automatically generated on Mon Feb 22 22:39:37 CST 2016
 */

    
package org.shaolin.bmdp.workflow.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.ITaskEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface ICreateWorkflow 
    extends IBusinessEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.bmdp.workflow.be.CreateWorkflow";
    
 
    /**
     *  get workflowName
     *
     *  @return workflowName
     */
    public java.lang.String getWorkflowName();

    /**
     *  get flowName
     *
     *  @return flowName
     */
    public java.lang.String getFlowName();

    /**
     *  get sessionServcies
     *
     *  @return sessionServcies
     */
    public java.util.List<ISessionVarDefinition> getSessionServcies();

    /**
     *  set workflowName
     */
    public void setWorkflowName(java.lang.String workflowName);

    /**
     *  set flowName
     */
    public void setFlowName(java.lang.String flowName);

    /**
     *  set sessionServcies
     */
    public void setSessionServcies(java.util.List<ISessionVarDefinition> sessionServcies);


}

        