/*
 *
 * This file is automatically generated on Mon Aug 07 14:08:46 CST 2017
 */

    
package org.shaolin.bmdp.persistence.be2;
        
import org.shaolin.bmdp.json.JSONException;
import org.shaolin.bmdp.json.JSONObject;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class PersonalInfoImpl2 
         implements IPersonalInfo
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    protected String getBusinessEntityName()
    {
        return "PersonalInfo";
    }

    public PersonalInfoImpl2()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String type;
    
        /**
     * Create Date
     */
    private java.util.Date createDate = null;

    /**
     * Enable record
     */
    private boolean _enable = true;

    /**
     * Cas record
     */
    private long _cas = 0;

    /**
     *  set orgId
     *  @parameter orgId.
     */
    private long orgId = 0;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected java.lang.String firstName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String lastName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String orgCode;
    
   /**
     *  help is not available
     */    
    protected OrganizationImpl2 organization;
    
   /**
     *  help is not available
     */    
    protected java.lang.String empId;
    
   /**
     *  help is not available
     */    
    protected int empLevelInt = 0;
    
   /**
     *  help is not available
     */    
    protected java.lang.String photoPath;
    
   /**
     *  help is not available
     */    
    protected boolean married;
    
   /**
     *  help is not available
     */    
    protected java.lang.String identityCardId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String discription;
    
   /**
     *  help is not available
     */    
    protected java.util.Date birthday;
    
   /**
     *  help is not available
     */    
    protected java.util.Date birthdayStart;
    
   /**
     *  help is not available
     */    
    protected java.util.Date birthdayEnd;
    
   /**
     *  help is not available
     */    
    
    protected int languageInt = 0;
    
   /**
     *  help is not available
     */    
    protected int educationInt = 0;
    
   /**
     *  help is not available
     */    
    protected java.lang.String major;
    
   /**
     *  help is not available
     */    
   /**
     *  help is not available
     */    
    protected java.util.Date startCreateDate;
    
   /**
     *  help is not available
     */    
    protected java.util.Date endCreateDate;
    
   /**
     *  help is not available
     */    
    protected java.lang.String comment;
    
        /**
     *  Get createDate
     *
     *  @return java.util.Date
     */
    public java.util.Date getCreateDate() {
        return createDate;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
            /**
     *  Get cas id.
     *
     *  @return long
     */
    public long getCas() {
        return _cas;
    }
            private long get_cas() {
        return _cas;
    }
            
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get type
     *
     *  @return type
     */
    public java.lang.String getType() {
        return type;
    }
    
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set type
     */
    public void setType(java.lang.String type) {
        this.type = type;
    }
            
    /**
     *  get orgId
     */
    public long getOrgId() {
        return this.orgId;
    }

    
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get firstName
     *
     *  @return firstName
     */
    public java.lang.String getFirstName() {
        return firstName;
    }

    /**
     *  get lastName
     *
     *  @return lastName
     */
    public java.lang.String getLastName() {
        return lastName;
    }

    /**
     *  get orgCode
     *
     *  @return orgCode
     */
    public java.lang.String getOrgCode() {
        return orgCode;
    }

    /**
     *  get organization
     *
     *  @return organization
     */
    public OrganizationImpl2 getOrganization() {
        return organization;
    }

    /**
     *  get empId
     *
     *  @return empId
     */
    public java.lang.String getEmpId() {
        return empId;
    }

    /**
     *  get empLevelInt
     *
     *  @return empLevelInt
     */
    private int getEmpLevelInt() {
        return empLevelInt;
    }

    /**
     *  get photoPath
     *
     *  @return photoPath
     */
    public java.lang.String getPhotoPath() {
        return photoPath;
    }

    /**
     *  get married
     *
     *  @return married
     */
    public boolean getMarried() {
        return married;
    }

    /**
     *  get identityCardId
     *
     *  @return identityCardId
     */
    public java.lang.String getIdentityCardId() {
        return identityCardId;
    }

    /**
     *  get discription
     *
     *  @return discription
     */
    public java.lang.String getDiscription() {
        return discription;
    }

    /**
     *  get birthday
     *
     *  @return birthday
     */
    public java.util.Date getBirthday() {
        return birthday;
    }

    /**
     *  get birthdayStart
     *
     *  @return birthdayStart
     */
    public java.util.Date getBirthdayStart() {
        return birthdayStart;
    }

    /**
     *  get birthdayEnd
     *
     *  @return birthdayEnd
     */
    public java.util.Date getBirthdayEnd() {
        return birthdayEnd;
    }

    /**
     *  get languageInt
     *
     *  @return languageInt
     */
    private int getLanguageInt() {
        return languageInt;
    }

    /**
     *  get educationInt
     *
     *  @return educationInt
     */
    private int getEducationInt() {
        return educationInt;
    }

    /**
     *  get major
     *
     *  @return major
     */
    public java.lang.String getMajor() {
        return major;
    }

    /**
     *  get startCreateDate
     *
     *  @return startCreateDate
     */
    public java.util.Date getStartCreateDate() {
        return startCreateDate;
    }

    /**
     *  get endCreateDate
     *
     *  @return endCreateDate
     */
    public java.util.Date getEndCreateDate() {
        return endCreateDate;
    }

    /**
     *  get comment
     *
     *  @return comment
     */
    public java.lang.String getComment() {
        return comment;
    }

        /**
     *  set createDate
     *  @parameter true or false.
     */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

        /**
     *  set cas
     *  @parameter true or false.
     */
    public void setCas(long cas) {
        _cas = cas;
    }

        private void set_cas(long cas) {
        _cas = cas;
    }

        /**
     *  set orgId
     *  @parameter orgId.
     */
    public void setOrgId(long orgId) {
        this.orgId = orgId;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set firstName
     */
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }

    /**
     *  set lastName
     */
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }

    /**
     *  set orgCode
     */
    public void setOrgCode(java.lang.String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     *  set organization
     */
    public void setOrganization(OrganizationImpl2 organization) {
        this.organization = organization;
    }

    public void setOrganization(IOrganization organization) {
        this.organization = (OrganizationImpl2)organization;
    }

    /**
     *  set empId
     */
    public void setEmpId(java.lang.String empId) {
        this.empId = empId;
    }

    /**
     *  set int empLevel
     */
    private void setEmpLevelInt(int intValue) {
        this.empLevelInt = intValue;
    }

    /**
     *  set photoPath
     */
    public void setPhotoPath(java.lang.String photoPath) {
        this.photoPath = photoPath;
    }

    /**
     *  set married
     */
    public void setMarried(boolean married) {
        this.married = married;
    }

    /**
     *  set identityCardId
     */
    public void setIdentityCardId(java.lang.String identityCardId) {
        this.identityCardId = identityCardId;
    }

    /**
     *  set discription
     */
    public void setDiscription(java.lang.String discription) {
        this.discription = discription;
    }

    /**
     *  set birthday
     */
    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    /**
     *  set birthdayStart
     */
    public void setBirthdayStart(java.util.Date birthdayStart) {
        this.birthdayStart = birthdayStart;
    }

    /**
     *  set birthdayEnd
     */
    public void setBirthdayEnd(java.util.Date birthdayEnd) {
        this.birthdayEnd = birthdayEnd;
    }

    /**
     *  set int language
     */
    private void setLanguageInt(int intValue) {
        this.languageInt = intValue;
    }


    /**
     *  set int education
     */
    private void setEducationInt(int intValue) {
        this.educationInt = intValue;
    }

    /**
     *  set major
     */
    public void setMajor(java.lang.String major) {
        this.major = major;
    }

    /**
     *  set startCreateDate
     */
    public void setStartCreateDate(java.util.Date startCreateDate) {
        this.startCreateDate = startCreateDate;
    }

    /**
     *  set endCreateDate
     */
    public void setEndCreateDate(java.util.Date endCreateDate) {
        this.endCreateDate = endCreateDate;
    }

    /**
     *  set comment
     */
    public void setComment(java.lang.String comment) {
        this.comment = comment;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof PersonalInfoImpl2))
            return false;
        PersonalInfoImpl2 o = (PersonalInfoImpl2)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        JSONObject json = new JSONObject(this);
        return json.toString();
    }
    
    public IPersonalInfo createEntity ()
    {
        return new PersonalInfoImpl2();
    }

	@Override
	public JSONObject toJSON() throws JSONException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void fromJSON(JSONObject json) throws JSONException {
		// TODO Auto-generated method stub
		
	}
    
}

        

