//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.30 at 11:19:59 PM CST 
//


package org.shaolin.bmdp.datamodel.workflow;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import org.shaolin.bmdp.datamodel.common.ExpressionType;


/**
 * <p>Java class for missionActionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="missionActionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="expression" type="{http://bmdp.shaolin.org/datamodel/Common}ExpressionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="actionPage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="actionName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="actionText" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="beforeActionWidget" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nextActionWidget" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "missionActionType", propOrder = {
    "expression"
})
public class MissionActionType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected ExpressionType expression;
    @XmlAttribute(name = "actionPage")
    protected String actionPage;
    @XmlAttribute(name = "actionName")
    protected String actionName;
    @XmlAttribute(name = "actionText")
    protected String actionText;
    @XmlAttribute(name = "beforeActionWidget")
    protected String beforeActionWidget;
    @XmlAttribute(name = "nextActionWidget")
    protected String nextActionWidget;

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link ExpressionType }
     *     
     */
    public ExpressionType getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpressionType }
     *     
     */
    public void setExpression(ExpressionType value) {
        this.expression = value;
    }

    /**
     * Gets the value of the actionPage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionPage() {
        return actionPage;
    }

    /**
     * Sets the value of the actionPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionPage(String value) {
        this.actionPage = value;
    }

    /**
     * Gets the value of the actionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * Sets the value of the actionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionName(String value) {
        this.actionName = value;
    }

    /**
     * Gets the value of the actionText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionText() {
        return actionText;
    }

    /**
     * Sets the value of the actionText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionText(String value) {
        this.actionText = value;
    }

    /**
     * Gets the value of the beforeActionWidget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeforeActionWidget() {
        return beforeActionWidget;
    }

    /**
     * Sets the value of the beforeActionWidget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeforeActionWidget(String value) {
        this.beforeActionWidget = value;
    }

    /**
     * Gets the value of the nextActionWidget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextActionWidget() {
        return nextActionWidget;
    }

    /**
     * Sets the value of the nextActionWidget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextActionWidget(String value) {
        this.nextActionWidget = value;
    }

}
