/*
 *
 * This file is automatically generated on Mon Aug 07 14:08:46 CST 2017
 */

    
package org.shaolin.bmdp.persistence.be;
        
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IOrganization 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.Organization";
    
 
    /**
     *  get parentId
     *
     *  @return parentId
     */
    public long getParentId();

    /**
     *  get orgCode
     *
     *  @return orgCode
     */
    public java.lang.String getOrgCode();

    /**
     *  get name
     *
     *  @return name
     */
    public java.lang.String getName();

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription();

    /**
     *  get addressId
     *
     *  @return addressId
     */
    public long getAddressId();

    /**
     *  get verifierId
     *
     *  @return verifierId
     */
    public long getVerifierId();

    /**
     *  set parentId
     */
    public void setParentId(long parentId);

    /**
     *  set orgCode
     */
    public void setOrgCode(java.lang.String orgCode);

    /**
     *  set name
     */
    public void setName(java.lang.String name);

    /**
     *  set description
     */
    public void setDescription(java.lang.String description);

    /**
     *  set addressId
     */
    public void setAddressId(long addressId);

    /**
     *  set verifierId
     */
    public void setVerifierId(long verifierId);


}

        