/*
 *
 * This file is automatically generated on Mon Aug 07 14:08:46 CST 2017
 */

    
package org.shaolin.bmdp.persistence.be;
        
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IPersonalInfo 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.vogerp.commonmodel.be.PersonalInfo";
    
 
    /**
     *  get orgId
     *
     *  @return orgId
     */
    public long getOrgId();

    /**
     *  set orgId
     */
    public void setOrgId(long orgId);

    /**
     *  get firstName
     *
     *  @return firstName
     */
    public java.lang.String getFirstName();

    /**
     *  get lastName
     *
     *  @return lastName
     */
    public java.lang.String getLastName();

    /**
     *  get orgCode
     *
     *  @return orgCode
     */
    public java.lang.String getOrgCode();

    /**
     *  get organization
     *
     *  @return organization
     */
    public OrganizationImpl getOrganization();

    /**
     *  get empId
     *
     *  @return empId
     */
    public java.lang.String getEmpId();

    /**
     *  get photoPath
     *
     *  @return photoPath
     */
    public java.lang.String getPhotoPath();

    /**
     *  get married
     *
     *  @return married
     */
    public boolean getMarried();

    /**
     *  get identityCardId
     *
     *  @return identityCardId
     */
    public java.lang.String getIdentityCardId();

    /**
     *  get discription
     *
     *  @return discription
     */
    public java.lang.String getDiscription();

    /**
     *  get birthday
     *
     *  @return birthday
     */
    public java.util.Date getBirthday();

    /**
     *  get birthdayStart
     *
     *  @return birthdayStart
     */
    public java.util.Date getBirthdayStart();

    /**
     *  get birthdayEnd
     *
     *  @return birthdayEnd
     */
    public java.util.Date getBirthdayEnd();

    /**
     *  get major
     *
     *  @return major
     */
    public java.lang.String getMajor();

    /**
     *  get startCreateDate
     *
     *  @return startCreateDate
     */
    public java.util.Date getStartCreateDate();

    /**
     *  get endCreateDate
     *
     *  @return endCreateDate
     */
    public java.util.Date getEndCreateDate();

    /**
     *  get comment
     *
     *  @return comment
     */
    public java.lang.String getComment();

    /**
     *  set firstName
     */
    public void setFirstName(java.lang.String firstName);

    /**
     *  set lastName
     */
    public void setLastName(java.lang.String lastName);

    /**
     *  set orgCode
     */
    public void setOrgCode(java.lang.String orgCode);

    /**
     *  set organization
     */
    public void setOrganization(OrganizationImpl organization);

    public void setOrganization(IOrganization organization);

    /**
     *  set empId
     */
    public void setEmpId(java.lang.String empId);

    /**
     *  set photoPath
     */
    public void setPhotoPath(java.lang.String photoPath);

    /**
     *  set married
     */
    public void setMarried(boolean married);

    /**
     *  set identityCardId
     */
    public void setIdentityCardId(java.lang.String identityCardId);

    /**
     *  set discription
     */
    public void setDiscription(java.lang.String discription);

    /**
     *  set birthday
     */
    public void setBirthday(java.util.Date birthday);

    /**
     *  set birthdayStart
     */
    public void setBirthdayStart(java.util.Date birthdayStart);

    /**
     *  set birthdayEnd
     */
    public void setBirthdayEnd(java.util.Date birthdayEnd);

    /**
     *  set major
     */
    public void setMajor(java.lang.String major);

    /**
     *  set startCreateDate
     */
    public void setStartCreateDate(java.util.Date startCreateDate);

    /**
     *  set endCreateDate
     */
    public void setEndCreateDate(java.util.Date endCreateDate);

    /**
     *  set comment
     */
    public void setComment(java.lang.String comment);


}

        