/*
 *
 * This file is automatically generated on Mon Aug 07 14:08:46 CST 2017
 */

    
package org.shaolin.bmdp.persistence.be;
        
import org.shaolin.bmdp.json.JSONException;
import org.shaolin.bmdp.json.JSONObject;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;


/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class OrganizationImpl 
         implements IOrganization
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    protected String getBusinessEntityName()
    {
        return "org.shaolin.vogerp.commonmodel.be.Organization";
    }

    public OrganizationImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String type;
    
        /**
     * Create Date
     */
    private java.util.Date createDate = null;

    /**
     * Enable record
     */
    private boolean _enable = true;

    /**
     * Cas record
     */
    private long _cas = 0;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long parentId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String orgCode;
    
   /**
     *  help is not available
     */    
    protected java.lang.String name;
    
   /**
     *  help is not available
     */    
    protected java.lang.String description;
    
   /**
     *  help is not available
     */    
    protected long addressId;
    
   /**
     *  help is not available
     */    
    protected long verifierId;
    
        /**
     *  Get createDate
     *
     *  @return java.util.Date
     */
    public java.util.Date getCreateDate() {
        return createDate;
    }
    
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get type
     *
     *  @return type
     */
    public java.lang.String getType() {
        return type;
    }
    
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set type
     */
    public void setType(java.lang.String type) {
        this.type = type;
    }
    
    /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
            /**
     *  Get cas id.
     *
     *  @return long
     */
    public long getCas() {
        return _cas;
    }
            private long get_cas() {
        return _cas;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get parentId
     *
     *  @return parentId
     */
    public long getParentId() {
        return parentId;
    }

    /**
     *  get orgCode
     *
     *  @return orgCode
     */
    public java.lang.String getOrgCode() {
        return orgCode;
    }

    /**
     *  get name
     *
     *  @return name
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     *  get description
     *
     *  @return description
     */
    public java.lang.String getDescription() {
        return description;
    }

    /**
     *  get addressId
     *
     *  @return addressId
     */
    public long getAddressId() {
        return addressId;
    }

    /**
     *  get verifierId
     *
     *  @return verifierId
     */
    public long getVerifierId() {
        return verifierId;
    }

        /**
     *  set createDate
     *  @parameter true or false.
     */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

        /**
     *  set cas
     *  @parameter true or false.
     */
    public void setCas(long cas) {
        _cas = cas;
    }

        private void set_cas(long cas) {
        _cas = cas;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set parentId
     */
    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    /**
     *  set orgCode
     */
    public void setOrgCode(java.lang.String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     *  set name
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    /**
     *  set description
     */
    public void setDescription(java.lang.String description) {
        this.description = description;
    }

    /**
     *  set addressId
     */
    public void setAddressId(long addressId) {
        this.addressId = addressId;
    }


    /**
     *  set verifierId
     */
    public void setVerifierId(long verifierId) {
        this.verifierId = verifierId;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof OrganizationImpl))
            return false;
        OrganizationImpl o = (OrganizationImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        JSONObject json = new JSONObject(this);
        return json.toString();
    }
    
    public IOrganization createEntity ()
    {
        return new OrganizationImpl();
    }

	@Override
	public JSONObject toJSON() throws JSONException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void fromJSON(JSONObject json) throws JSONException {
		// TODO Auto-generated method stub
		
	}
    
}

        

