/*
 *
 * This file is automatically generated on Sat Mar 12 13:14:24 CST 2016
 */

    
package org.shaolin.bmdp.analyzer.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.ITaskEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class ChartPointDataImpl  implements org.shaolin.bmdp.analyzer.be.IChartPointData
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final transient IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.bmdp.analyzer.be.ChartPointData";
    }

    public ChartPointDataImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Create Date
     */
    private java.util.Date createDate = null;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected java.lang.String label;
    
   /**
     *  help is not available
     */    
    protected java.lang.String dataset;
    
   /**
     *  help is not available
     */    
    protected java.lang.String dataset1;
    
   /**
     *  help is not available
     */    
    protected java.lang.String dataset2;
    
   /**
     *  help is not available
     */    
    protected java.lang.String dataset3;
    
   /**
     *  help is not available
     */    
    protected java.lang.String dataset4;
    
        /**
     *  Get createDate
     *
     *  @return java.util.Date
     */
    public java.util.Date getCreateDate() {
        return createDate;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get label
     *
     *  @return label
     */
    public java.lang.String getLabel() {
        return label;
    }

    /**
     *  get dataset
     *
     *  @return dataset
     */
    public java.lang.String getDataset() {
        return dataset;
    }

    /**
     *  get dataset1
     *
     *  @return dataset1
     */
    public java.lang.String getDataset1() {
        return dataset1;
    }

    /**
     *  get dataset2
     *
     *  @return dataset2
     */
    public java.lang.String getDataset2() {
        return dataset2;
    }

    /**
     *  get dataset3
     *
     *  @return dataset3
     */
    public java.lang.String getDataset3() {
        return dataset3;
    }

    /**
     *  get dataset4
     *
     *  @return dataset4
     */
    public java.lang.String getDataset4() {
        return dataset4;
    }

        /**
     *  set createDate
     *  @parameter true or false.
     */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set label
     */
    public void setLabel(java.lang.String label) {
        this.label = label;
    }

    /**
     *  set dataset
     */
    public void setDataset(java.lang.String dataset) {
        this.dataset = dataset;
    }

    /**
     *  set dataset1
     */
    public void setDataset1(java.lang.String dataset1) {
        this.dataset1 = dataset1;
    }

    /**
     *  set dataset2
     */
    public void setDataset2(java.lang.String dataset2) {
        this.dataset2 = dataset2;
    }

    /**
     *  set dataset3
     */
    public void setDataset3(java.lang.String dataset3) {
        this.dataset3 = dataset3;
    }

    /**
     *  set dataset4
     */
    public void setDataset4(java.lang.String dataset4) {
        this.dataset4 = dataset4;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.bmdp.analyzer.be.ChartPointDataImpl))
            return false;
        org.shaolin.bmdp.analyzer.be.ChartPointDataImpl o = (org.shaolin.bmdp.analyzer.be.ChartPointDataImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.bmdp.analyzer.be.ChartPointData");
    
        aBuf.append(" : ");
        
        aBuf.append("createDate=").append(createDate).append(", ");
        
        aBuf.append("label");
        aBuf.append("=");
        aBuf.append(label);
        aBuf.append(", ");
        
        aBuf.append("dataset");
        aBuf.append("=");
        aBuf.append(dataset);
        aBuf.append(", ");
        
        aBuf.append("dataset1");
        aBuf.append("=");
        aBuf.append(dataset1);
        aBuf.append(", ");
        
        aBuf.append("dataset2");
        aBuf.append("=");
        aBuf.append(dataset2);
        aBuf.append(", ");
        
        aBuf.append("dataset3");
        aBuf.append("=");
        aBuf.append(dataset3);
        aBuf.append(", ");
        
        aBuf.append("dataset4");
        aBuf.append("=");
        aBuf.append(dataset4);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.StringType labelBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for label
        member = new MemberType();
        member.setName("label");
        member.setDescription("null");
        member.setType(labelBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType datasetBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for dataset
        member = new MemberType();
        member.setName("dataset");
        member.setDescription("null");
        member.setType(datasetBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType dataset1BEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for dataset1
        member = new MemberType();
        member.setName("dataset1");
        member.setDescription("null");
        member.setType(dataset1BEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType dataset2BEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for dataset2
        member = new MemberType();
        member.setName("dataset2");
        member.setDescription("null");
        member.setType(dataset2BEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType dataset3BEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for dataset3
        member = new MemberType();
        member.setName("dataset3");
        member.setDescription("null");
        member.setType(dataset3BEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType dataset4BEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for dataset4
        member = new MemberType();
        member.setName("dataset4");
        member.setDescription("null");
        member.setType(dataset4BEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IChartPointData createEntity ()
    {
        return new ChartPointDataImpl();
    }
    
}

        

