/*
 *
 * This file is automatically generated on Sun Mar 13 11:14:55 CST 2016
 */

    
package org.shaolin.bmdp.analyzer.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.ITaskEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public class ChartStatisticImpl  implements org.shaolin.bmdp.analyzer.be.IChartStatistic
{
    private static final long serialVersionUID = 0x90B1123CE87B50FFL;

    private final transient IConstantService ceService = AppContext.get().getConstantService();

    protected String getBusinessEntityName()
    {
        return "org.shaolin.bmdp.analyzer.be.ChartStatistic";
    }

    public ChartStatisticImpl()
    {
        
        _extField = new BEExtensionInfo();
        
    }
    
    
        /**
     * Create Date
     */
    private java.util.Date createDate = null;

    /**
     * Enable record
     */
    private boolean _enable = true;


    /**
     *  BEExtension _extType
     */
    protected String _extType;

    /**
     *  BEExtension _extField
     */
    protected BEExtensionInfo _extField;
        
   /**
     *  help is not available
     */    
    protected long id;
    
   /**
     *  help is not available
     */    
    protected java.lang.String actionOnUIFrom;
    
   /**
     *  help is not available
     */    
    protected java.lang.String actionOnWidgetId;
    
   /**
     *  help is not available
     */    
    protected java.lang.String statsTableName;
    
   /**
     *  help is not available
     */    
    protected java.lang.String statsUIFrom;
    
   /**
     *  help is not available
     */    
    protected java.lang.String chartType;
    
        /**
     *  Get createDate
     *
     *  @return java.util.Date
     */
    public java.util.Date getCreateDate() {
        return createDate;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    public boolean isEnabled() {
        return _enable;
    }
            /**
     *  Is enable
     *
     *  @return boolean
     */
    private boolean get_enable() {
        return _enable;
    }
        
    /**
     *  get _extType
     *
     *  @return _extType
     */
    public String get_extType() {
        return _extType;
    }

    /**
     *  get _extField
     *
     *  @return _extField
     */
    public BEExtensionInfo get_extField() {
        return _extField;
    }
        
    /**
     *  get id
     *
     *  @return id
     */
    public long getId() {
        return id;
    }

    /**
     *  get actionOnUIFrom
     *
     *  @return actionOnUIFrom
     */
    public java.lang.String getActionOnUIFrom() {
        return actionOnUIFrom;
    }

    /**
     *  get actionOnWidgetId
     *
     *  @return actionOnWidgetId
     */
    public java.lang.String getActionOnWidgetId() {
        return actionOnWidgetId;
    }

    /**
     *  get statsTableName
     *
     *  @return statsTableName
     */
    public java.lang.String getStatsTableName() {
        return statsTableName;
    }

    /**
     *  get statsUIFrom
     *
     *  @return statsUIFrom
     */
    public java.lang.String getStatsUIFrom() {
        return statsUIFrom;
    }

    /**
     *  get chartType
     *
     *  @return chartType
     */
    public java.lang.String getChartType() {
        return chartType;
    }

        /**
     *  set createDate
     *  @parameter true or false.
     */
    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    public void setEnabled(boolean enable) {
        _enable = enable;
    }

        /**
     *  set enable
     *  @parameter true or false.
     */
    private void set_enable(boolean enable) {
        _enable = enable;
    }

    /**
     *  set _extType
     *  @param _extType which is the extension type of be object.
     */
    public void set_extType(java.lang.String _extType) {
        this._extType = _extType;
    }
        
    /**
     *  set id
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     *  set actionOnUIFrom
     */
    public void setActionOnUIFrom(java.lang.String actionOnUIFrom) {
        this.actionOnUIFrom = actionOnUIFrom;
    }

    /**
     *  set actionOnWidgetId
     */
    public void setActionOnWidgetId(java.lang.String actionOnWidgetId) {
        this.actionOnWidgetId = actionOnWidgetId;
    }

    /**
     *  set statsTableName
     */
    public void setStatsTableName(java.lang.String statsTableName) {
        this.statsTableName = statsTableName;
    }

    /**
     *  set statsUIFrom
     */
    public void setStatsUIFrom(java.lang.String statsUIFrom) {
        this.statsUIFrom = statsUIFrom;
    }

    /**
     *  set chartType
     */
    public void setChartType(java.lang.String chartType) {
        this.chartType = chartType;
    }

    
    /**
     * Check different according to primary key.
     */
    public boolean equals(Object obj) {
        if (obj == this)
            return true;
        if (!(obj instanceof org.shaolin.bmdp.analyzer.be.ChartStatisticImpl))
            return false;
        org.shaolin.bmdp.analyzer.be.ChartStatisticImpl o = (org.shaolin.bmdp.analyzer.be.ChartStatisticImpl)obj;
        
        boolean result = super.equals(obj);

        boolean eq = true;
        
        return result;
    }

    /**
     * Generate hashCode according to primary key.
     */
    public int hashCode() {
        
        int result = super.hashCode();

        return result;
    }
        
    
     /**
     * Gets the String format of the business entity.
     *
     * @return String the business entity in String format.
     */
    public  String  toString() {
        StringBuffer aBuf = new StringBuffer();
        aBuf.append("org.shaolin.bmdp.analyzer.be.ChartStatistic");
    
        aBuf.append(" : ");
        
        aBuf.append("createDate=").append(createDate).append(", ");
        
        aBuf.append("enable=").append(_enable).append(", ");
        
        aBuf.append("id");
        aBuf.append("=");
        aBuf.append(id);
        aBuf.append(", ");
        
        aBuf.append("actionOnUIFrom");
        aBuf.append("=");
        aBuf.append(actionOnUIFrom);
        aBuf.append(", ");
        
        aBuf.append("actionOnWidgetId");
        aBuf.append("=");
        aBuf.append(actionOnWidgetId);
        aBuf.append(", ");
        
        aBuf.append("statsTableName");
        aBuf.append("=");
        aBuf.append(statsTableName);
        aBuf.append(", ");
        
        aBuf.append("statsUIFrom");
        aBuf.append("=");
        aBuf.append(statsUIFrom);
        aBuf.append(", ");
        
        aBuf.append("chartType");
        aBuf.append("=");
        aBuf.append(chartType);
        aBuf.append(", ");
        
        return aBuf.toString();
    }
    
    
     /**
     * Gets list of MemberType.
     *
     * @return List     the list of MemberType.
     */
    public List<MemberType> getMemberList() {
        List<MemberType> memberTypeList = new ArrayList<MemberType>();
        
        MemberType member = null;
        
        org.shaolin.bmdp.datamodel.bediagram.LongType idBEType = new org.shaolin.bmdp.datamodel.bediagram.LongType();
    
        //MemberType Define for id
        member = new MemberType();
        member.setName("id");
        member.setDescription("null");
        member.setType(idBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType actionOnUIFromBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for actionOnUIFrom
        member = new MemberType();
        member.setName("actionOnUIFrom");
        member.setDescription("null");
        member.setType(actionOnUIFromBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType actionOnWidgetIdBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for actionOnWidgetId
        member = new MemberType();
        member.setName("actionOnWidgetId");
        member.setDescription("null");
        member.setType(actionOnWidgetIdBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType statsTableNameBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for statsTableName
        member = new MemberType();
        member.setName("statsTableName");
        member.setDescription("null");
        member.setType(statsTableNameBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType statsUIFromBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for statsUIFrom
        member = new MemberType();
        member.setName("statsUIFrom");
        member.setDescription("null");
        member.setType(statsUIFromBEType);
        memberTypeList.add(member);
            
        org.shaolin.bmdp.datamodel.bediagram.StringType chartTypeBEType = new org.shaolin.bmdp.datamodel.bediagram.StringType();
    
        //MemberType Define for chartType
        member = new MemberType();
        member.setName("chartType");
        member.setDescription("null");
        member.setType(chartTypeBEType);
        memberTypeList.add(member);
            
        return memberTypeList;
    }
    
    public IChartStatistic createEntity ()
    {
        return new ChartStatisticImpl();
    }
    
}

        

