/*
 *
 * This file is automatically generated on Sun Mar 13 11:14:55 CST 2016
 */

    
package org.shaolin.bmdp.analyzer.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.ITaskEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IChartStatistic 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.bmdp.analyzer.be.ChartStatistic";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get actionOnUIFrom
     *
     *  @return actionOnUIFrom
     */
    public java.lang.String getActionOnUIFrom();

    /**
     *  get actionOnWidgetId
     *
     *  @return actionOnWidgetId
     */
    public java.lang.String getActionOnWidgetId();

    /**
     *  get statsTableName
     *
     *  @return statsTableName
     */
    public java.lang.String getStatsTableName();

    /**
     *  get statsUIFrom
     *
     *  @return statsUIFrom
     */
    public java.lang.String getStatsUIFrom();

    /**
     *  get chartType
     *
     *  @return chartType
     */
    public java.lang.String getChartType();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set actionOnUIFrom
     */
    public void setActionOnUIFrom(java.lang.String actionOnUIFrom);

    /**
     *  set actionOnWidgetId
     */
    public void setActionOnWidgetId(java.lang.String actionOnWidgetId);

    /**
     *  set statsTableName
     */
    public void setStatsTableName(java.lang.String statsTableName);

    /**
     *  set statsUIFrom
     */
    public void setStatsUIFrom(java.lang.String statsUIFrom);

    /**
     *  set chartType
     */
    public void setChartType(java.lang.String chartType);


}

        