/*
 *
 * This file is automatically generated on Fri Mar 04 21:03:57 CST 2016
 */

    
package org.shaolin.bmdp.analyzer.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.ITaskEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IJob 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.bmdp.analyzer.be.Job";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get jarPath
     *
     *  @return jarPath
     */
    public java.lang.String getJarPath();

    /**
     *  get mainClass
     *
     *  @return mainClass
     */
    public java.lang.String getMainClass();

    /**
     *  get taskId
     *
     *  @return taskId
     */
    public long getTaskId();

    /**
     *  get task
     *
     *  @return task
     */
    public org.shaolin.bmdp.workflow.be.TaskImpl getTask();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set jarPath
     */
    public void setJarPath(java.lang.String jarPath);

    /**
     *  set mainClass
     */
    public void setMainClass(java.lang.String mainClass);

    /**
     *  set taskId
     */
    public void setTaskId(long taskId);

    /**
     *  set task
     */
    public void setTask(org.shaolin.bmdp.workflow.be.TaskImpl task);


}

        