/*
 *
 * This file is automatically generated on Sun Apr 03 21:42:15 CST 2016
 */

    
package org.shaolin.bmdp.analyzer.be;
        
import java.util.Collections;
import java.util.List;
import java.util.ArrayList;

import org.shaolin.bmdp.datamodel.bediagram.*;
import org.shaolin.bmdp.datamodel.common.*;
import org.shaolin.bmdp.runtime.be.IBusinessEntity;
import org.shaolin.bmdp.runtime.be.IExtensibleEntity;
import org.shaolin.bmdp.runtime.be.IPersistentEntity;
import org.shaolin.bmdp.runtime.be.IHistoryEntity;
import org.shaolin.bmdp.runtime.be.ITaskEntity;
import org.shaolin.bmdp.runtime.be.BEExtensionInfo;

import org.shaolin.bmdp.runtime.spi.IConstantService;

import org.shaolin.bmdp.runtime.AppContext;

import org.shaolin.bmdp.runtime.ce.CEUtil;



/**
 * null
 * 
 * This code is generated automatically, any change will be replaced after rebuild.
 * 
 *
 */

public interface IPageHelper 
    extends IPersistentEntity, IExtensibleEntity
{
    public final static String ENTITY_NAME = "org.shaolin.bmdp.analyzer.be.PageHelper";
    
 
    /**
     *  get id
     *
     *  @return id
     */
    public long getId();

    /**
     *  get htmlFile
     *
     *  @return htmlFile
     */
    public java.lang.String getHtmlFile();

    /**
     *  get isMobileView
     *
     *  @return isMobileView
     */
    public boolean getIsMobileView();

    /**
     *  get partyType
     *
     *  @return partyType
     */
    public java.lang.String getPartyType();

    /**
     *  set id
     */
    public void setId(long id);

    /**
     *  set htmlFile
     */
    public void setHtmlFile(java.lang.String htmlFile);

    /**
     *  set isMobileView
     */
    public void setIsMobileView(boolean isMobileView);

    /**
     *  set partyType
     */
    public void setPartyType(java.lang.String partyType);


}

        